Description of genericFeederCandidateSelection
Home > src > genericFeederCandidateSelection.m
genericFeederCandidateSelection
PURPOSE
- parent class for replacement selection objects
SYNOPSIS
This is a script file.
DESCRIPTION
 - parent class for replacement selection objects
 copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
    This file is part of SOS
    SOS is free software: you can redistribute it and/or modify
    it for academic and non-commercial purposes
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.  For commercial or for-profit
    uses, please contact the authors (sos@cnbc.cmu.edu).
    SOS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
CROSS-REFERENCE INFORMATION
This function calls:
genericFeederCandidateSelection - parent class for replacement selection objects
sample - sample object
This function is called by:
genericFeederCandidateSelection - parent class for replacement selection objects
randPopulationAndSampleCandidateSelection - random population and sample selection method for swaps
randPopulationCandidateSelection - random population selection method for selecting swaps
SOURCE CODE
% - parent class for replacement selection objects
%
% copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
%
%    This file is part of SOS
%
%    SOS is free software: you can redistribute it and/or modify
%    it for academic and non-commercial purposes
%    under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.  For commercial or for-profit
%    uses, please contact the authors (sos@cnbc.cmu.edu).
%
%    SOS is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%    You should have received a copy of the GNU General Public License
%    along with SOS (see COPYING.txt).
%    If not, see <http://www.gnu.org/licenses/>.
classdef genericFeederCandidateSelection < handle
    %% abstract interface defining required methods for selecting feeder items
    methods (Abstract)
        init(obj,sosObj);
        [feederdf,feederdfIndex] = getCandidateIndex(obj,sample);
    end
end