Description of genericStatTest
Home > src > genericStatTest.m
genericStatTest
PURPOSE
- parent class for statistical test objects
SYNOPSIS
This is a script file.
DESCRIPTION
 - parent class for statistical test objects
 copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
    This file is part of SOS
    SOS is free software: you can redistribute it and/or modify
    it for academic and non-commercial purposes
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.  For commercial or for-profit
    uses, please contact the authors (sos@cnbc.cmu.edu).
    SOS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
CROSS-REFERENCE INFORMATION
This function calls:
genericStatTest - parent class for statistical test objects
sosCorrelTest - test for equivalence of two correlations
soskstest - object for testing normality using a Kolmogorov-Smirnov test
sosttest - object for creating t-tests
This function is called by:
genericStatTest - parent class for statistical test objects
sos - SOS optimization object
sosttest - object for creating t-tests
SUBFUNCTIONS
function obj = createStatTest(test, varargin)
SOURCE CODE
% - parent class for statistical test objects
%
% copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
%
%    This file is part of SOS
%
%    SOS is free software: you can redistribute it and/or modify
%    it for academic and non-commercial purposes
%    under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.  For commercial or for-profit
%    uses, please contact the authors (sos@cnbc.cmu.edu).
%
%    SOS is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%    You should have received a copy of the GNU General Public License
%    along with SOS (see COPYING.txt).
%    If not, see <http://www.gnu.org/licenses/>.
classdef genericStatTest < handle
    % parent class used to create statistical tests
    %
    % METHODS (Static)
    % createStatTest(test,varargin) % constructor for ttests
    methods (Static)
        function obj = createStatTest(test, varargin)
            if strcmp(test,'ttest')
                obj = sosttest(varargin{:});
            elseif strcmp(test,'matchCorrel')
                obj = sosCorrelTest(varargin{:});
            elseif strcmp(test,'matchUniform')
                obj = soskstest(varargin{:});
            else
                error(['Unsupported stat test: ',test]);
            end
        end
    end
end