Description of getdfName
Home > src > getdfName.m
getdfName
PURPOSE
- extracts a dataframe name selected in the GUI
SYNOPSIS
function dfName = getdfName(handle,dfType)
DESCRIPTION
 -  extracts a dataframe name selected in the GUI
 copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
    This file is part of SOS
    SOS is free software: you can redistribute it and/or modify
    it for academic and non-commercial purposes
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.  For commercial or for-profit
    uses, please contact the authors (sos@cnbc.cmu.edu).
    SOS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
calculateOverlap_Dialog - calculate overlap dialog
create2samplettest_Dialog - create 2-sample t-test dialog
createHardBoundConstraint_Dialog - create hard bound constraint dialog
createMatchCorrelztest_Dialog - create correlation-matching z-test dialog
createMatchUniformkstest_Dialog - create uniformity ks-test dialog
createPlots_Dialog - create sosplots dialog
createSingleSampleSoftDistanceConstraint_Dialog - create single sample soft distance constraint dialog
createSoftEntropyConstraint_Dialog - create soft entropy constraint dialog
createSoftMatchCorrelDistanceConstraint_Dialog - create soft match correlation constraint dialog
createSoftMetaConstraint_Dialog - create soft meta-constraint dialog
createTwoSampleSoftDistanceConstraint_Dialog - create two sample soft distance constraint dialog
createsinglesamplettest_Dialog - create single sample t-test dialog
expAnneal_Dialog - create expAnneal dialog
saveHistory_Dialog - dialog used to save the optimization history
setBufferedHistoryOutfile_Dialog - dialog for setting output file for buffered history output
sos_gui - sos main GUI
SOURCE CODE
% -  extracts a dataframe name selected in the GUI
%
% copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
%
%    This file is part of SOS
%
%    SOS is free software: you can redistribute it and/or modify
%    it for academic and non-commercial purposes
%    under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.  For commercial or for-profit
%    uses, please contact the authors (sos@cnbc.cmu.edu).
%
%    SOS is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%    You should have received a copy of the GNU General Public License
%    along with SOS (see COPYING.txt).
%    If not, see <http://www.gnu.org/licenses/>.
% returns the string label of the dataframe (techically and more generally now, the
% name of the object) that has been selected in a gui popup menu.
function dfName = getdfName(handle,dfType)
    %% returns the string label (name) of an object in a gui popup menu
    dfNum = get(handle,'Value');
    dfNames = get(handle,'String');
    if isempty(dfNames) == 0
        if ischar(dfNames) % for if there is only one entry in the list
            dfName = dfNames;
        else
            dfName = dfNames{dfNum};
        end
    else
        dfName = '';
    end
    %make sure there is an active df
    if isempty(dfName) == 0
        % success
    else
        msgbox(['A ',dfType,' must be active'],...
                ['No active ',dfType]);
    end