Description of sos_gui
Home > src > sos_gui.m
sos_gui
PURPOSE
- sos main GUI
SYNOPSIS
function varargout = sos_gui(varargin)
DESCRIPTION
 - sos main GUI
 copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
    This file is part of SOS
    SOS is free software: you can redistribute it and/or modify
    it for academic and non-commercial purposes
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.  For commercial or for-profit
    uses, please contact the authors (sos@cnbc.cmu.edu).
    SOS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
CROSS-REFERENCE INFORMATION
This function calls:
calculateOverlap_Dialog - calculate overlap dialog
create2samplettest_Dialog - create 2-sample t-test dialog
createHardBoundConstraint_Dialog - create hard bound constraint dialog
createMatchCorrelztest_Dialog - create correlation-matching z-test dialog
createMatchUniformkstest_Dialog - create uniformity ks-test dialog
createPlots_Dialog - create sosplots dialog
createPop_Dialog - create population dialog
createSOS_dialog - create SOS optimizer dialog
createSample_Dialog - create sample dialog
createSingleSampleSoftDistanceConstraint_Dialog - create single sample soft distance constraint dialog
createSoftEntropyConstraint_Dialog - create soft entropy constraint dialog
createSoftMatchCorrelDistanceConstraint_Dialog - create soft match correlation constraint dialog
createSoftMetaConstraint_Dialog - create soft meta-constraint dialog
createTwoSampleSoftDistanceConstraint_Dialog - create two sample soft distance constraint dialog
createsinglesamplettest_Dialog - create single sample t-test dialog
expAnneal_Dialog - create expAnneal dialog
getdfName - extracts a dataframe name selected in the GUI
maxpDecrease_Dialog dialog used for calculating the largest p-decrease value
numSteps_Dialog dialog used to calculate the nubmer of temperature-lowering steps
saveHistory_Dialog - dialog used to save the optimization history
setBufferedHistoryOutfile_Dialog - dialog for setting output file for buffered history output
setSeed_Dialog - dialog for setting the random seed
validatePositiveInteger - helper function to validate that a string represents a positive integer
verbosePrint - master print function that regulates cmd line output based on verbosity flags
This function is called by:
create2samplettest_Dialog - create 2-sample t-test dialog
createHardBoundConstraint_Dialog - create hard bound constraint dialog
createMatchCorrelztest_Dialog - create correlation-matching z-test dialog
createMatchUniformkstest_Dialog - create uniformity ks-test dialog
createPlots_Dialog - create sosplots dialog
createSingleSampleSoftDistanceConstraint_Dialog - create single sample soft distance constraint dialog
createSoftEntropyConstraint_Dialog - create soft entropy constraint dialog
createSoftMatchCorrelDistanceConstraint_Dialog - create soft match correlation constraint dialog
createSoftMetaConstraint_Dialog - create soft meta-constraint dialog
createTwoSampleSoftDistanceConstraint_Dialog - create two sample soft distance constraint dialog
createsinglesamplettest_Dialog - create single sample t-test dialog
expAnneal_Dialog - create expAnneal dialog
saveHistory_Dialog - dialog used to save the optimization history
setBufferedHistoryOutfile_Dialog - dialog for setting output file for buffered history output
sos - SOS optimization object
SUBFUNCTIONS
function sos_gui_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = sos_gui_OutputFcn(hObject, eventdata, handles)
function edit_CmdWindow_Callback(hObject, eventdata, handles)
function edit_CmdWindow_CreateFcn(hObject, eventdata, handles)
function pushbutton_runScript_Callback(hObject, eventdata, handles)
function pushbutton_CreatePopulation_Callback(hObject, eventdata, handles)
function edit_CmdWindow_KeyPressFcn(hObject, eventdata, handles)
function popupmenu_popSelector_Callback(hObject, eventdata, handles)
function popupmenu_popSelector_CreateFcn(hObject, eventdata, handles)
function populatePopList(hObject)
function populateSampleList(hObject)
function pushbutton_popWriteData_Callback(hObject, eventdata, handles)
function writedf(handle,dfType)
function popupmenu_popSelector_ButtonDownFcn(hObject, eventdata, handles)
function popupmenu_popSelector_KeyPressFcn(hObject, eventdata, handles)
function pushbutton_refreshPopList_Callback(hObject, eventdata, handles)
function pushbutton_createSample_Callback(hObject, eventdata, handles)
function popupmenu_sampleSelector_Callback(hObject, eventdata, handles)
function popupmenu_sampleSelector_CreateFcn(hObject, eventdata, handles)
function pushbutton_writeSampleData_Callback(hObject, eventdata, handles)
function pushbutton_refreshSampleList_Callback(hObject, eventdata, handles)
function pushbutton_createSample_CreateFcn(hObject, eventdata, handles)
function popupmenu_sampleSelector_ButtonDownFcn(hObject, eventdata, handles)
function pushbutton_setPop_Callback(hObject, eventdata, handles)
function pushbutton_sampleLock_Callback(hObject, eventdata, handles)
function execSimpleCmd(handle,dfType,cmd)
function pushbutton_sampleUnlock_Callback(hObject, eventdata, handles)
function pushbutton_createSOS_Callback(hObject, eventdata, handles)
function pushbutton_refresh_SOSlist_Callback(hObject, eventdata, handles)
function popupmenu_SOSSelector_Callback(hObject, eventdata, handles)
function popupmenu_SOSSelector_CreateFcn(hObject, eventdata, handles)
function populateSOSList(hObject)
function popupmenu_sampleSelector_KeyPressFcn(hObject, eventdata, handles)
function popupmenu_SOSSelector_ButtonDownFcn(hObject, eventdata, handles)
function pushbutton_addSample_Callback(hObject, eventdata, handles)
function pushbutton_createHistory_Callback(hObject, eventdata, handles)
function pushbutton_createPlots_Callback(hObject, eventdata, handles)
function edit_dispIt_Callback(hObject, eventdata, handles)
function edit_dispIt_CreateFcn(hObject, eventdata, handles)
function pushbutton_deltaCostPercentiles_Callback(hObject, eventdata, handles)
function pushbutton_writeHistory_Callback(hObject, eventdata, handles)
function pushbutton_writeSamples_Callback(hObject, eventdata, handles)
function pushbutton_writePopulations_Callback(hObject, eventdata, handles)
function pushbutton_dispCost_Callback(hObject, eventdata, handles)
function pushbutton_initCost_Callback(hObject, eventdata, handles)
function pushbutton_writeAll_Callback(hObject, eventdata, handles)
function pushbutton_initFillSamples_Callback(hObject, eventdata, handles)
function pushbutton_normalizeData_Callback(hObject, eventdata, handles)
function pushbutton_setSeed_Callback(hObject, eventdata, handles)
function pushbutton_setBufferedHistoryOutfile_Callback(hObject, eventdata, handles)
function pushbutton28_Callback(hObject, eventdata, handles)
function pushbutton_enableBufferedHistoryWrite_Callback(hObject, eventdata, handles)
function pushbutton_disableBufferedHistoryWrite_Callback(hObject, eventdata, handles)
function popupmenu_reportStyleSelector_Callback(hObject, eventdata, handles)
function popupmenu_reportStyleSelector_CreateFcn(hObject, eventdata, handles)
function pushbutton_doStatsTests_Callback(hObject, eventdata, handles)
function pushbutton_setFeederdfCandidateSelectionMethod_Callback(hObject, eventdata, handles)
function popupmenu_feederdfCandSelectMethod_Callback(hObject, eventdata, handles)
function popupmenu_feederdfCandSelectMethod_CreateFcn(hObject, eventdata, handles)
function pushbutton_greedyAnneal_Callback(hObject, eventdata, handles)
function pushbutton_expAnneal_Callback(hObject, eventdata, handles)
function pushbutton_numSteps_Callback(hObject, eventdata, handles)
function pushbutton_maxpDecrease_Callback(hObject, eventdata, handles)
function pushbutton_optimize_Callback(hObject, eventdata, handles)
function pushbutton_stopOptimize_Callback(hObject, eventdata, handles)
function edit_numIt_Callback(hObject, eventdata, handles)
function flag = validate_numIt(handles)
function edit_numIt_CreateFcn(hObject, eventdata, handles)
function pushbutton_stopOptimize_CreateFcn(hObject, eventdata, handles)
function pushbutton_2sample_ttest_Callback(hObject, eventdata, handles)
function pushbutton_singlettest_Callback(hObject, eventdata, handles)
function pushbutton_createHardBoundConstraint_Callback(hObject, eventdata, handles)
function pushbutton_createSingleSampleSoftDistanceConstraint_Callback(hObject, eventdata, handles)
function pushbutton_create2SampleSoftDistanceConstraint_Callback(hObject, eventdata, handles)
function pushbutton_createSoftEntropyConstraint_Callback(hObject, eventdata, handles)
function popupmenu_entropyConstraintSelector_Callback(hObject, eventdata, handles)
function populateEntropyConstraintList(hObject)
function popupmenu_entropyConstraintSelector_CreateFcn(hObject, eventdata, handles)
function pushbutton_plotSoftEntropyConstraint_Callback(hObject, eventdata, handles)
function pushbutton_refreshSoftEntropyConstraintSelector_Callback(hObject, eventdata, handles)
function pushbutton_createSoftMetaConstraint_Callback(hObject, eventdata, handles)
function pushbutton_calculateOverlap_Callback(hObject, eventdata, handles)
function pushbutton_createSoftMatchCorrelConstraint_Callback(hObject, eventdata, handles)
function pushbutton_matchCorrel_ztest_Callback(hObject, eventdata, handles)
function pushbutton_kstest_Callback(hObject, eventdata, handles)
SOURCE CODE
% - sos main GUI
%
% copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
%
%    This file is part of SOS
%
%    SOS is free software: you can redistribute it and/or modify
%    it for academic and non-commercial purposes
%    under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.  For commercial or for-profit
%    uses, please contact the authors (sos@cnbc.cmu.edu).
%
%    SOS is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%    You should have received a copy of the GNU General Public License
%    along with SOS (see COPYING.txt).
%    If not, see <http://www.gnu.org/licenses/>.
function varargout = sos_gui(varargin)
% SOS_GUI M-file for sos_gui.fig
%      SOS_GUI, by itself, creates a new SOS_GUI or raises the existing
%      singleton*.
%
%      H = SOS_GUI returns the handle to a new SOS_GUI or the handle to
%      the existing singleton*.
%
%      SOS_GUI('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in SOS_GUI.M with the given input arguments.
%
%      SOS_GUI('Property','Value',...) creates a new SOS_GUI or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before sos_gui_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to sos_gui_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES
% Edit the above text to modify the response to help sos_gui
% Last Modified by GUIDE v2.5 16-Aug-2011 17:46:24
%
% BCA:
% Note: the following warning has been disabled.
% warning('off','MATLAB:hg:uicontrol:ParameterValuesMustBeValid');
% It occurs when the active population/sample lists are empty.
%
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @sos_gui_OpeningFcn, ...
                   'gui_OutputFcn',  @sos_gui_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before sos_gui is made visible.
function sos_gui_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to sos_gui (see VARARGIN)
% Choose default command line output for sos_gui
handles.output = hObject;
% Update handles structure
guidata(hObject, handles);
% UIWAIT makes sos_gui wait for user response (see UIRESUME)
% uiwait(handles.figure1);
disp([char(10),char(10),'SOS: Stochastic Optimization of Stimuli',char(10),...
'    Copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut',char(10),...
char(10),...
'    This binary executable is part of SOS',char(10),...
char(10),...
'    SOS is free software: you can redistribute it and/or modify',char(10),...
'    it for academic and non-commercial purposes',char(10),...
'    under the terms of the GNU General Public License as published by',char(10),...
'    the Free Software Foundation, either version 3 of the License, or',char(10),...
'    (at your option) any later version.  For commercial or for-profit',char(10),...
'    uses, please contact the authors (sos@cnbc.cmu.edu).',char(10),...
char(10),...
'    SOS is distributed in the hope that it will be useful,',char(10),...
'    but WITHOUT ANY WARRANTY; without even the implied warranty of',char(10),...
'    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the',char(10),...
'    GNU General Public License for more details.',char(10),...
char(10),...
'    You should have received a copy of the GNU General Public License',char(10),...
'    along with SOS (see COPYING.txt).',char(10),...
'    If not, see <http://www.gnu.org/licenses/>.',char(10),char(10),char(10)]);
% --- Outputs from this function are returned to the command line.
function varargout = sos_gui_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Get default command line output from handles structure
varargout{1} = handles.output;
function edit_CmdWindow_Callback(hObject, eventdata, handles)
% hObject    handle to edit_CmdWindow (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_CmdWindow as text
%        str2double(get(hObject,'String')) returns contents of edit_CmdWindow as a double
    % technically, the command line will try to run whenever you loose
    % focus.  However, there doesn't seem to be an easy workaround (e.g.,
    % conditioning on carriage returns didn't seem to stop the call back).
    command = get(hObject,'String');
    verbosePrint(['Evaluating GUI command: ', command], ...
            'sos_gui_cmdWindow_CallBack_runcmd');
    evalin('base',command);
    set(hObject,'String','');
    % END edit_CmdWindow CALLBACK
% --- Executes during object creation, after setting all properties.
function edit_CmdWindow_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_CmdWindow (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
    set(hObject, 'KeyPressFcn', @edit_CmdWindow_KeyPressFcn);
% --- Executes on button press in pushbutton_runScript.
function pushbutton_runScript_Callback(hObject, eventdata, handles)
    % hObject    handle to pushbutton_runScript (see GCBO)
    % eventdata  reserved - to be defined in a future version of MATLAB
    % handles    structure with handles and user data (see GUIDATA)
    % let user navigate to the script to run
    [fileName,pathName] = uigetfile('*','Run Script...');
    if fileName ~= 0
        fullName = strcat(pathName,fileName);
        % try to run the script...
        verbosePrint(['Running script: ', fullName], ...
                    'sos_gui_runScript_CallBack_runScript');
        cd(pathName);
        %first, read in the script:
        try
            fid = fopen(fullName,'r');
        catch exception
            error(['Could not open file: ', fullName]);
        end
        try
            script = fscanf(fid,'%c');
        catch
             error(['Error while reading file: ', fullName]);
        end
        %run the script
        evalin('base',script);
    end
    % END runScript CALLBACK
% --- Executes on button press in pushbutton_CreatePopulation.
function pushbutton_CreatePopulation_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_CreatePopulation (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    createPop_Dialog();
% --- Executes on key press with focus on edit_CmdWindow and none of its controls.
function edit_CmdWindow_KeyPressFcn(hObject, eventdata, handles)
% hObject    handle to edit_CmdWindow (see GCBO)
% eventdata  structure with the following fields (see UICONTROL)
%    Key: name of the key that was pressed, in lower case
%    Character: character interpretation of the key(s) that was pressed
%    Modifier: name(s) of the modifier key(s) (i.e., control, shift) pressed
% handles    structure with handles and user data (see GUIDATA)
% --- Executes on selection change in popupmenu_popSelector.
function popupmenu_popSelector_Callback(hObject, eventdata, handles)
% hObject    handle to popupmenu_popSelector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_popSelector contents as cell array
%        contents{get(hObject,'Value')} returns selected item from popupmenu_popSelector
    populatePopList(hObject);
% --- Executes during object creation, after setting all properties.
function popupmenu_popSelector_CreateFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_popSelector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
    %populatePopList(hObject);
% populates the population list
function populatePopList(hObject)
    % get a list of all populations in the base workspace:
    vars = evalin('base','whos()');
    pops = [];
    for i=1:length(vars)
        if strcmp(vars(i).class,'population')
            pops = [pops; {vars(i).name}]; %#ok<AGROW>
        end
    end
    %in case no populations are present, set to the empty string:
    if isempty(pops)
        pops = '';
    end
    % assign that list to the options in the pop up menu.  Disable warnings
    % if the list is empty and then re-enable them.
    warning('off','MATLAB:hg:uicontrol:ParameterValuesMustBeValid');
    set(hObject,'String',pops);
% populates the sample list
function populateSampleList(hObject)
    % get a list of all populations in the base workspace:
    vars = evalin('base','whos()');
    samples = [];
    for i=1:length(vars)
        if strcmp(vars(i).class,'sample')
            samples = [samples; {vars(i).name}]; %#ok<AGROW>
        end
    end
    % assign that list to the options in the pop up menu
    warning('off','MATLAB:hg:uicontrol:ParameterValuesMustBeValid');
    set(hObject,'String',samples);
% --- Executes on button press in pushbutton_popWriteData.
function pushbutton_popWriteData_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_popWriteData (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    menuHandle = handles.popupmenu_popSelector;
    writedf(menuHandle,'population');
function writedf(handle,dfType)
    % get the active population's name
    dfNum = get(handle,'Value');
    dfNames = get(handle,'String');
    if isempty(dfNames) == 0
        dfName = dfNames{dfNum};
    else
        dfName = '';
    end
    %make sure there is an active population
    if isempty(dfName) == 0
        command = strcat(dfName,'.writeData()');
        verbosePrint(['Executing command: ','''',command,''''],'sosGui_writeDF');
        evalin('base',command);
    else
        msgbox(['A ',dfType,' must be active to write data'],...
                ['No active ',dfType]);
    end
% --- If Enable == 'on', executes on mouse press in 5 pixel border.
% --- Otherwise, executes on mouse press in 5 pixel border or over popupmenu_popSelector.
function popupmenu_popSelector_ButtonDownFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_popSelector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    populatePopList(hObject);
% --- Executes on key press with focus on popupmenu_popSelector and none of its controls.
function popupmenu_popSelector_KeyPressFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_popSelector (see GCBO)
% eventdata  structure with the following fields (see UICONTROL)
%    Key: name of the key that was pressed, in lower case
%    Character: character interpretation of the key(s) that was pressed
%    Modifier: name(s) of the modifier key(s) (i.e., control, shift) pressed
% handles    structure with handles and user data (see GUIDATA)
% --- Executes on button press in pushbutton_refreshPopList.
function pushbutton_refreshPopList_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_refreshPopList (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    % refresh the list of populations
    populatePopList(handles.popupmenu_popSelector);
% --- Executes on button press in pushbutton_createSample.
function pushbutton_createSample_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_createSample (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    createSample_Dialog();
% --- Executes on selection change in popupmenu_sampleSelector.
function popupmenu_sampleSelector_Callback(hObject, eventdata, handles)
% hObject    handle to popupmenu_sampleSelector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_sampleSelector contents as cell array
%        contents{get(hObject,'Value')} returns selected item from popupmenu_sampleSelector
    populateSampleList(hObject);
% --- Executes during object creation, after setting all properties.
function popupmenu_sampleSelector_CreateFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_sampleSelector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on button press in pushbutton_writeSampleData.
function pushbutton_writeSampleData_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_writeSampleData (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    menuHandle = handles.popupmenu_sampleSelector;
    writedf(menuHandle,'sample');
% --- Executes on button press in pushbutton_refreshSampleList.
function pushbutton_refreshSampleList_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_refreshSampleList (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    populateSampleList(handles.popupmenu_sampleSelector);
% --- Executes during object creation, after setting all properties.
function pushbutton_createSample_CreateFcn(hObject, eventdata, handles)
% hObject    handle to pushbutton_createSample (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% --- If Enable == 'on', executes on mouse press in 5 pixel border.
% --- Otherwise, executes on mouse press in 5 pixel border or over popupmenu_sampleSelector.
function popupmenu_sampleSelector_ButtonDownFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_sampleSelector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    populateSampleList(hObject);
% --- Executes on button press in pushbutton_setPop.
function pushbutton_setPop_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_setPop (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    %two things to do: first, make sure that there is an active population.
    % Second, make sure that there is an active sample.
    link = true;
    popMenuHandle = handles.popupmenu_popSelector;
    popName = getdfName(popMenuHandle,'population');
    if isempty(popName)
        link = false;
    end
    if link == true
        sampleMenuHandle = handles.popupmenu_sampleSelector;
        sampleName = getdfName(sampleMenuHandle,'sample');
        if isempty(sampleName)
            link = false;
        end
        if link == true
            % we have valid samples and populations.  Link them.
            command = [sampleName,'.setPop(',popName,');'];
            verbosePrint(['Executing command: ','''',command,''''],'sosGui_links2p');
            evalin('base',command);
        end
    end
% retrieves the name of a dataframe from the active lists of data frames
% function dfName = getdfName(handle,dfType)
%     dfNum = get(handle,'Value');
%     dfNames = get(handle,'String');
%
%     if isempty(dfNames) == 0
%         dfName = dfNames{dfNum};
%     else
%         dfName = '';
%     end
%
%     %make sure there is an active df
%     if isempty(dfName) == 0
%         % success
%     else
%         msgbox(['A ',dfType,' must be active'],...
%                 ['No active ',dfType]);
%     end
%
% --- Executes on button press in pushbutton_sampleLock.
function pushbutton_sampleLock_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_sampleLock (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    menuHandle = handles.popupmenu_sampleSelector;
    execSimpleCmd(menuHandle,'sample','lockAll()');
% provides functiona
function execSimpleCmd(handle,dfType,cmd)
    % get the active population's name
    dfNum = get(handle,'Value');
    dfNames = get(handle,'String');
    if isempty(dfNames) == 0
        dfName = dfNames{dfNum};
    else
        dfName = '';
    end
    %make sure there is an active population
    if isempty(dfName) == 0
        command = strcat(dfName,'.',cmd);
        verbosePrint(['Executing command: ','''',command,''''],'sosGui_simpleCmd');
        evalin('base',command);
    else
        msgbox(['A ',dfType,' must be active to run: ',cmd],...
                ['No active ',dfType]);
    end
% --- Executes on button press in pushbutton_sampleUnlock.
function pushbutton_sampleUnlock_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_sampleUnlock (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    menuHandle = handles.popupmenu_sampleSelector;
    execSimpleCmd(menuHandle,'sample','unlockAll()');
% --- Executes on button press in pushbutton_createSOS.
function pushbutton_createSOS_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_createSOS (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    createSOS_dialog();
% --- Executes on button press in pushbutton_refresh_SOSlist.
function pushbutton_refresh_SOSlist_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_refresh_SOSlist (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    populateSOSList(handles.popupmenu_SOSSelector);
% --- Executes on selection change in popupmenu_SOSSelector.
function popupmenu_SOSSelector_Callback(hObject, eventdata, handles)
% hObject    handle to popupmenu_SOSSelector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_SOSSelector contents as cell array
%        contents{get(hObject,'Value')} returns selected item from popupmenu_SOSSelector
    populateSOSList(hObject);
% --- Executes during object creation, after setting all properties.
function popupmenu_SOSSelector_CreateFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_SOSSelector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function populateSOSList(hObject)
    % get a list of all populations in the base workspace:
    vars = evalin('base','whos()');
    sosObjs = [];
    for i=1:length(vars)
        if strcmp(vars(i).class,'sos')
            sosObjs = [sosObjs; {vars(i).name}]; %#ok<AGROW>
        end
    end
    % assign that list to the options in the pop up menu
    warning('off','MATLAB:hg:uicontrol:ParameterValuesMustBeValid');
    set(hObject,'String',sosObjs);
% --- Executes on key press with focus on popupmenu_sampleSelector and none of its controls.
function popupmenu_sampleSelector_KeyPressFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_sampleSelector (see GCBO)
% eventdata  structure with the following fields (see UICONTROL)
%    Key: name of the key that was pressed, in lower case
%    Character: character interpretation of the key(s) that was pressed
%    Modifier: name(s) of the modifier key(s) (i.e., control, shift) pressed
% handles    structure with handles and user data (see GUIDATA)
% --- If Enable == 'on', executes on mouse press in 5 pixel border.
% --- Otherwise, executes on mouse press in 5 pixel border or over popupmenu_SOSSelector.
function popupmenu_SOSSelector_ButtonDownFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_SOSSelector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    populateSOSList(hObject);
% --- Executes on button press in pushbutton_addSample.
function pushbutton_addSample_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_addSample (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    add = true;
    %retrieve name of active sample
    sampleMenuHandle = handles.popupmenu_sampleSelector;
    sampleName = getdfName(sampleMenuHandle,'sample');
    if isempty(sampleName)
        add = false;
    end
    % if there is a valid active sample, add it.
    if add == true
        sosMenuHandle = handles.popupmenu_SOSSelector;
        sosName = getdfName(sosMenuHandle,'SOS');
        if isempty(sosName)
            add = false;
        end
        if add == true
            % we have a valid sample and a valid SOS object.  Add the
            % sample to the sos object
            command = [sosName,'.addSample(',sampleName,');'];
            verbosePrint(['Executing command: ','''',command,''''],'sosGui_addSample');
            evalin('base',command);
        end
    end
% --- Executes on button press in pushbutton_createHistory.
function pushbutton_createHistory_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_createHistory (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
        create = true;
        sosMenuHandle = handles.popupmenu_SOSSelector;
        sosName = getdfName(sosMenuHandle,'SOS');
        if isempty(sosName)
            create = false;
        end
        if create == true
            % create the history
            command = [sosName,'.createHistory();'];
            verbosePrint(['Executing command: ','''',command,''''],'sosGui_createHistory');
            evalin('base',command);
        end
% --- Executes on button press in pushbutton_createPlots.
function pushbutton_createPlots_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_createPlots (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    create = true;
        sosMenuHandle = handles.popupmenu_SOSSelector;
        sosName = getdfName(sosMenuHandle,'SOS');
        if isempty(sosName)
            create = false;
        end
        if create == true
            % run the createPlots dialog to give users choice of optional
            % params
            createPlots_Dialog();
        end
function edit_dispIt_Callback(hObject, eventdata, handles)
% hObject    handle to edit_dispIt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: get(hObject,'String') returns contents of edit_dispIt as text
%        str2double(get(hObject,'String')) returns contents of edit_dispIt as a double
% --- Executes during object creation, after setting all properties.
function edit_dispIt_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit_dispIt (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes on button press in pushbutton_deltaCostPercentiles.
function pushbutton_deltaCostPercentiles_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_deltaCostPercentiles (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
        run = true;
        sosMenuHandle = handles.popupmenu_SOSSelector;
        sosName = getdfName(sosMenuHandle,'SOS');
        if isempty(sosName)
            run = false;
        end
        if run == true
            % create the history
            command = [sosName,'.deltaCostPercentiles();'];
            verbosePrint(['Executing command: ','''',command,''''],'sosGui_deltaCostDeciles');
            evalin('base',command);
        end
% --- Executes on button press in pushbutton_writeHistory.
function pushbutton_writeHistory_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_writeHistory (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    saveHistory_Dialog();
% --- Executes on button press in pushbutton_writeSamples.
function pushbutton_writeSamples_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_writeSamples (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
        write = true;
        sosMenuHandle = handles.popupmenu_SOSSelector;
        sosName = getdfName(sosMenuHandle,'SOS');
        if isempty(sosName)
            write = false;
        end
        if write == true
            % create the history
            command = [sosName,'.writeSamples();'];
            verbosePrint(['Executing command: ','''',command,''''],'sosGui_writeSamples');
            evalin('base',command);
        end
% --- Executes on button press in pushbutton_writePopulations.
function pushbutton_writePopulations_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_writePopulations (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
        write = true;
        sosMenuHandle = handles.popupmenu_SOSSelector;
        sosName = getdfName(sosMenuHandle,'SOS');
        if isempty(sosName)
            write = false;
        end
        if write == true
            % create the history
            command = [sosName,'.writePopulations();'];
            verbosePrint(['Executing command: ','''',command,''''],'sosGui_writePopulations');
            evalin('base',command);
        end
% --- Executes on button press in pushbutton_dispCost.
function pushbutton_dispCost_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_dispCost (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
        write = true;
        sosMenuHandle = handles.popupmenu_SOSSelector;
        sosName = getdfName(sosMenuHandle,'SOS');
        if isempty(sosName)
            write = false;
        end
        if write == true
            % create the history
            command = [sosName,'.dispCost();'];
            verbosePrint(['Executing command: ','''',command,''''],'sosGui_dispCost');
            evalin('base',command);
        end
% --- Executes on button press in pushbutton_initCost.
function pushbutton_initCost_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_initCost (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
        write = true;
        sosMenuHandle = handles.popupmenu_SOSSelector;
        sosName = getdfName(sosMenuHandle,'SOS');
        if isempty(sosName)
            write = false;
        end
        if write == true
            % create the history
            command = [sosName,'.initCost();'];
            verbosePrint(['Executing command: ','''',command,''''],'sosGui_initCost');
            evalin('base',command);
        end
% --- Executes on button press in pushbutton_writeAll.
function pushbutton_writeAll_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_writeAll (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
        write = true;
        sosMenuHandle = handles.popupmenu_SOSSelector;
        sosName = getdfName(sosMenuHandle,'SOS');
        if isempty(sosName)
            write = false;
        end
        if write == true
            % create the history
            command = [sosName,'.writeAll();'];
            verbosePrint(['Executing command: ','''',command,''''],'sosGui_writeAll');
            evalin('base',command);
        end
% --- Executes on button press in pushbutton_initFillSamples.
function pushbutton_initFillSamples_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_initFillSamples (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
        write = true;
        sosMenuHandle = handles.popupmenu_SOSSelector;
        sosName = getdfName(sosMenuHandle,'SOS');
        if isempty(sosName)
            write = false;
        end
        if write == true
            % create the history
            command = [sosName,'.initFillSamples();'];
            verbosePrint(['Executing command: ','''',command,''''],'sosGui_initFillSamples');
            evalin('base',command);
        end
% --- Executes on button press in pushbutton_normalizeData.
function pushbutton_normalizeData_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_normalizeData (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
        write = true;
        sosMenuHandle = handles.popupmenu_SOSSelector;
        sosName = getdfName(sosMenuHandle,'SOS');
        if isempty(sosName)
            write = false;
        end
        if write == true
            % create the history
            command = [sosName,'.normalizeData();'];
            verbosePrint(['Executing command: ','''',command,''''],'sosGui_initFillSamples');
            evalin('base',command);
        end
% --- Executes on button press in pushbutton_setSeed.
function pushbutton_setSeed_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_setSeed (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    setSeed_Dialog();
% --- Executes on button press in pushbutton_setBufferedHistoryOutfile.
function pushbutton_setBufferedHistoryOutfile_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_setBufferedHistoryOutfile (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
    setBufferedHistoryOutfile_Dialog();
% --- Executes on button press in pushbutton28.
function pushbutton28_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton28 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% --- Executes on button press in pushbutton_enableBufferedHistoryWrite.
function pushbutton_enableBufferedHistoryWrite_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_enableBufferedHistoryWrite (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
        create = true;
        sosMenuHandle = handles.popupmenu_SOSSelector;
        sosName = getdfName(sosMenuHandle,'SOS');
        if isempty(sosName)
            create = false;
        end
        if create == true
            % create the history
            command = [sosName,'.enableBufferedHistoryWrite();'];
            verbosePrint(['Executing command: ','''',command,''''],'sosGui_enableBufferedHistory');
            evalin('base',command);
        end
% --- Executes on button press in pushbutton_disableBufferedHistoryWrite.
function pushbutton_disableBufferedHistoryWrite_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton_disableBufferedHistoryWrite (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
        create = true;
        sosMenuHandle = handles.popupmenu_SOSSelector;
        sosName = getdfName(sosMenuHandle,'SOS');
        if isempty(sosName)
            create = false;
        end
        if create == true
            % create the history
            command = [sosName,'.disableBufferedHistoryWrite();'];
            verbosePrint(['Executing command: ','''',command,''''],'sosGui_disableBufferedHistory');
            evalin('base',command);
        end
% --- Executes on selection change in popupmenu_reportStyleSelector.
function popupmenu_reportStyleSelector_Callback(hObject, eventdata, handles)
% hObject    handle to popupmenu_reportStyleSelector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_reportStyleSelector contents as cell array
%        contents{get(hObject,'Value')} returns selected item from popupmenu_reportStyleSelector
% --- Executes during object creation, after setting all properties.
function popupmenu_reportStyleSelector_CreateFcn(hObject, eventdata, handles)
% hObject    handle to popupmenu_reportStyleSelector (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
1000 % Hint: popupmenu controls usually have a white background on Windows.
1001 %       See ISPC and COMPUTER.
1002 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1003     set(hObject,'BackgroundColor','white');
1004 end
1005
1006
1007 % --- Executes on button press in pushbutton_doStatsTests.
1008 function pushbutton_doStatsTests_Callback(hObject, eventdata, handles)
1009 % hObject    handle to pushbutton_doStatsTests (see GCBO)
1010 % eventdata  reserved - to be defined in a future version of MATLAB
1011 % handles    structure with handles and user data (see GUIDATA)
1012
1013         run = true;
1014
1015         sosMenuHandle = handles.popupmenu_SOSSelector;
1016         sosName = getdfName(sosMenuHandle,'SOS');
1017
1018         if isempty(sosName)
1019             run = false;
1020         end
1021
1022         if run == true
1023
1024             % retrieve the reportStyle
1025
1026             styleMenuHandle = handles.popupmenu_reportStyleSelector;
1027             style = getdfName(styleMenuHandle,'reportStyle');
1028
1029             % create the history
1030             command = [sosName,'.doStatTests(''reportStyle'',''',style,''');'];
1031
1032             verbosePrint(['Executing command: ','''',command,''''],'sosGui_doStats');
1033             evalin('base',command);
1034         end
1035
1036
1037 % --- Executes on button press in pushbutton_setFeederdfCandidateSelectionMethod.
1038 function pushbutton_setFeederdfCandidateSelectionMethod_Callback(hObject, eventdata, handles)
1039 % hObject    handle to pushbutton_setFeederdfCandidateSelectionMethod (see GCBO)
1040 % eventdata  reserved - to be defined in a future version of MATLAB
1041 % handles    structure with handles and user data (see GUIDATA)
1042         set = true;
1043
1044         sosMenuHandle = handles.popupmenu_SOSSelector;
1045         sosName = getdfName(sosMenuHandle,'SOS');
1046
1047         if isempty(sosName)
1048             set = false;
1049         end
1050
1051         if set == true
1052
1053             modeMenuHandle = handles.popupmenu_feederdfCandSelectMethod;
1054             mode = getdfName(modeMenuHandle,'neighborMode');
1055
1056             % create the history
1057             command = [sosName,'.setFeederdfCandidateSelectionMethod(''',mode,''');'];
1058
1059             verbosePrint(['Executing command: ','''',command,''''],'sosGui_setFeederdfCandMethod');
1060             evalin('base',command);
1061         end
1062
1063 % --- Executes on selection change in popupmenu_feederdfCandSelectMethod.
1064 function popupmenu_feederdfCandSelectMethod_Callback(hObject, eventdata, handles)
1065 % hObject    handle to popupmenu_feederdfCandSelectMethod (see GCBO)
1066 % eventdata  reserved - to be defined in a future version of MATLAB
1067 % handles    structure with handles and user data (see GUIDATA)
1068
1069 % Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_feederdfCandSelectMethod contents as cell array
1070 %        contents{get(hObject,'Value')} returns selected item from popupmenu_feederdfCandSelectMethod
1071
1072
1073 % --- Executes during object creation, after setting all properties.
1074 function popupmenu_feederdfCandSelectMethod_CreateFcn(hObject, eventdata, handles)
1075 % hObject    handle to popupmenu_feederdfCandSelectMethod (see GCBO)
1076 % eventdata  reserved - to be defined in a future version of MATLAB
1077 % handles    empty - handles not created until after all CreateFcns called
1078
1079 % Hint: popupmenu controls usually have a white background on Windows.
1080 %       See ISPC and COMPUTER.
1081 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1082     set(hObject,'BackgroundColor','white');
1083 end
1084
1085
1086 % --- Executes on button press in pushbutton_greedyAnneal.
1087 function pushbutton_greedyAnneal_Callback(hObject, eventdata, handles)
1088 % hObject    handle to pushbutton_greedyAnneal (see GCBO)
1089 % eventdata  reserved - to be defined in a future version of MATLAB
1090 % handles    structure with handles and user data (see GUIDATA)
1091         set = true;
1092
1093         sosMenuHandle = handles.popupmenu_SOSSelector;
1094         sosName = getdfName(sosMenuHandle,'SOS');
1095
1096         if isempty(sosName)
1097             set = false;
1098         end
1099
1100         if set == true
1101             % create the history
1102             command = [sosName,'.setAnnealSchedule(''schedule'',''greedy'');'];
1103
1104             verbosePrint(['Executing command: ','''',command,''''],'sosGui_greedyAnneal');
1105             evalin('base',command);
1106         end
1107
1108
1109 % --- Executes on button press in pushbutton_expAnneal.
1110 function pushbutton_expAnneal_Callback(hObject, eventdata, handles)
1111 % hObject    handle to pushbutton_expAnneal (see GCBO)
1112 % eventdata  reserved - to be defined in a future version of MATLAB
1113 % handles    structure with handles and user data (see GUIDATA)
1114     expAnneal_Dialog();
1115
1116
1117 % --- Executes on button press in pushbutton_numSteps.
1118 function pushbutton_numSteps_Callback(hObject, eventdata, handles)
1119 % hObject    handle to pushbutton_numSteps (see GCBO)
1120 % eventdata  reserved - to be defined in a future version of MATLAB
1121 % handles    structure with handles and user data (see GUIDATA)
1122     numSteps_Dialog();
1123
1124 % --- Executes on button press in pushbutton_maxpDecrease.
1125 function pushbutton_maxpDecrease_Callback(hObject, eventdata, handles)
1126 % hObject    handle to pushbutton_maxpDecrease (see GCBO)
1127 % eventdata  reserved - to be defined in a future version of MATLAB
1128 % handles    structure with handles and user data (see GUIDATA)
1129     maxpDecrease_Dialog();
1130
1131
1132 % --- Executes on button press in pushbutton_optimize.
1133 function pushbutton_optimize_Callback(hObject, eventdata, handles)
1134 % hObject    handle to pushbutton_optimize (see GCBO)
1135 % eventdata  reserved - to be defined in a future version of MATLAB
1136 % handles    structure with handles and user data (see GUIDATA)
1137
1138   %  disp('STOPPING');
1139
1140
1141     set(handles.pushbutton_stopOptimize,'UserData',0);
1142     run = true;
1143
1144     sosMenuHandle = handles.popupmenu_SOSSelector;
1145     sosName = getdfName(sosMenuHandle,'SOS');
1146
1147     if isempty(sosName)
1148         run = false;
1149     end
1150
1151     if run == true
1152
1153         % if the number of iterations to run for is blank, run
1154         numIt = (get(handles.edit_numIt,'String'));
1155
1156        set(handles.pushbutton_stopOptimize,'Enable','on');
1157
1158         if isempty(numIt)
1159         %
1160             command = [sosName,'.optimize(''isGui'',1);'];
1161             verbosePrint(['Executing command: ','''',command,''''],'sosGui_optimize');
1162
1163             set(handles.pushbutton_optimize,'Enable','off');
1164             evalin('base',command);
1165
1166         elseif validate_numIt(handles)
1167             command = [sosName,'.optimize(',numIt,',''isGui'',1);'];
1168             verbosePrint(['Executing command: ','''',command,''''],'sosGui_optimize');
1169
1170             set(handles.pushbutton_optimize,'Enable','off');
1171             evalin('base',command);
1172
1173         end
1174     end
1175
1176
1177 % --- Executes on button press in pushbutton_stopOptimize.
1178 function pushbutton_stopOptimize_Callback(hObject, eventdata, handles)
1179 % hObject    handle to pushbutton_stopOptimize (see GCBO)
1180 % eventdata  reserved - to be defined in a future version of MATLAB
1181 % handles    structure with handles and user data (see GUIDATA)
1182
1183   %  disp('STOPPING');
1184     set(handles.pushbutton_stopOptimize,'UserData',1);
1185     %guidata(hObject,handles);
1186     set(handles.pushbutton_stopOptimize,'Enable','off');
1187     set(handles.pushbutton_optimize,'Enable','on');
1188
1189
1190 function edit_numIt_Callback(hObject, eventdata, handles)
1191 % hObject    handle to edit_numIt (see GCBO)
1192 % eventdata  reserved - to be defined in a future version of MATLAB
1193 % handles    structure with handles and user data (see GUIDATA)
1194
1195 % Hints: get(hObject,'String') returns contents of edit_numIt as text
1196 %        str2double(get(hObject,'String')) returns contents of edit_numIt as a double
1197     validate_numIt(handles);
1198
1199
1200 function flag = validate_numIt(handles)
1201     str = get(handles.edit_numIt,'String');
1202
1203     if isempty(str)
1204         flag = 1; % valid if empty
1205     else
1206
1207         errmsg = 'Number of iterations must be a whole number > 0';
1208         errtitle = 'Invalid numIt!';
1209
1210         flag = validatePositiveInteger(str,errmsg,errtitle);
1211     end
1212
1213
1214 % --- Executes during object creation, after setting all properties.
1215 function edit_numIt_CreateFcn(hObject, eventdata, handles)
1216 % hObject    handle to edit_numIt (see GCBO)
1217 % eventdata  reserved - to be defined in a future version of MATLAB
1218 % handles    empty - handles not created until after all CreateFcns called
1219
1220 % Hint: edit controls usually have a white background on Windows.
1221 %       See ISPC and COMPUTER.
1222 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1223     set(hObject,'BackgroundColor','white');
1224 end
1225
1226
1227 % --- Executes during object creation, after setting all properties.
1228 function pushbutton_stopOptimize_CreateFcn(hObject, eventdata, handles)
1229 % hObject    handle to pushbutton_stopOptimize (see GCBO)
1230 % eventdata  reserved - to be defined in a future version of MATLAB
1231 % handles    empty - handles not created until after all CreateFcns called
1232
1233
1234 % --- Executes on button press in pushbutton_2sample_ttest.
1235 function pushbutton_2sample_ttest_Callback(hObject, eventdata, handles)
1236 % hObject    handle to pushbutton_2sample_ttest (see GCBO)
1237 % eventdata  reserved - to be defined in a future version of MATLAB
1238 % handles    structure with handles and user data (see GUIDATA)
1239         create = true;
1240
1241         sosMenuHandle = handles.popupmenu_SOSSelector;
1242         sosName = getdfName(sosMenuHandle,'SOS');
1243
1244         if isempty(sosName)
1245             create = false;
1246         end
1247
1248         if create == true
1249             create2samplettest_Dialog();
1250         end
1251
1252
1253
1254
1255
1256
1257 % --- Executes on button press in pushbutton_singlettest.
1258 function pushbutton_singlettest_Callback(hObject, eventdata, handles)
1259 % hObject    handle to pushbutton_singlettest (see GCBO)
1260 % eventdata  reserved - to be defined in a future version of MATLAB
1261 % handles    structure with handles and user data (see GUIDATA)
1262         create = true;
1263
1264         sosMenuHandle = handles.popupmenu_SOSSelector;
1265         sosName = getdfName(sosMenuHandle,'SOS');
1266
1267         if isempty(sosName)
1268             create = false;
1269         end
1270
1271         if create == true
1272             createsinglesamplettest_Dialog();
1273         end
1274
1275
1276 % --- Executes on button press in pushbutton_createHardBoundConstraint.
1277 function pushbutton_createHardBoundConstraint_Callback(hObject, eventdata, handles)
1278 % hObject    handle to pushbutton_createHardBoundConstraint (see GCBO)
1279 % eventdata  reserved - to be defined in a future version of MATLAB
1280 % handles    structure with handles and user data (see GUIDATA)
1281     createHardBoundConstraint_Dialog();
1282
1283 % --- Executes on button press in pushbutton_createSingleSampleSoftDistanceConstraint.
1284 function pushbutton_createSingleSampleSoftDistanceConstraint_Callback(hObject, eventdata, handles)
1285 % hObject    handle to pushbutton_createSingleSampleSoftDistanceConstraint (see GCBO)
1286 % eventdata  reserved - to be defined in a future version of MATLAB
1287 % handles    structure with handles and user data (see GUIDATA)
1288     createSingleSampleSoftDistanceConstraint_Dialog();
1289
1290 % --- Executes on button press in pushbutton_create2SampleSoftDistanceConstraint.
1291 function pushbutton_create2SampleSoftDistanceConstraint_Callback(hObject, eventdata, handles)
1292 % hObject    handle to pushbutton_create2SampleSoftDistanceConstraint (see GCBO)
1293 % eventdata  reserved - to be defined in a future version of MATLAB
1294 % handles    structure with handles and user data (see GUIDATA)
1295     createTwoSampleSoftDistanceConstraint_Dialog();
1296
1297
1298 % --- Executes on button press in pushbutton_createSoftEntropyConstraint.
1299 function pushbutton_createSoftEntropyConstraint_Callback(hObject, eventdata, handles)
1300 % hObject    handle to pushbutton_createSoftEntropyConstraint (see GCBO)
1301 % eventdata  reserved - to be defined in a future version of MATLAB
1302 % handles    structure with handles and user data (see GUIDATA)
1303     createSoftEntropyConstraint_Dialog();
1304
1305
1306 % --- Executes on selection change in popupmenu_entropyConstraintSelector.
1307 function popupmenu_entropyConstraintSelector_Callback(hObject, eventdata, handles)
1308 % hObject    handle to popupmenu_entropyConstraintSelector (see GCBO)
1309 % eventdata  reserved - to be defined in a future version of MATLAB
1310 % handles    structure with handles and user data (see GUIDATA)
1311     populateEntropyConstraintList(hObject);
1312
1313 % Hints: contents = cellstr(get(hObject,'String')) returns popupmenu_entropyConstraintSelector contents as cell array
1314 %        contents{get(hObject,'Value')} returns selected item from popupmenu_entropyConstraintSelector
1315 function populateEntropyConstraintList(hObject)
1316     % get a list of all populations in the base workspace:
1317     vars = evalin('base','whos()');
1318
1319     cObjs = [];
1320     for i=1:length(vars)
1321         if strcmp(vars(i).class,'softEntropyConstraint')
1322             cObjs = [cObjs; {vars(i).name}]; %#ok<AGROW>
1323         end
1324     end
1325
1326
1327
1328     % assign that list to the options in the pop up menu
1329     warning('off','MATLAB:hg:uicontrol:ParameterValuesMustBeValid');
1330     set(hObject,'String',cObjs);
1331
1332
1333
1334 % --- Executes during object creation, after setting all properties.
1335 function popupmenu_entropyConstraintSelector_CreateFcn(hObject, eventdata, handles)
1336 % hObject    handle to popupmenu_entropyConstraintSelector (see GCBO)
1337 % eventdata  reserved - to be defined in a future version of MATLAB
1338 % handles    empty - handles not created until after all CreateFcns called
1339
1340 % Hint: popupmenu controls usually have a white background on Windows.
1341 %       See ISPC and COMPUTER.
1342 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1343     set(hObject,'BackgroundColor','white');
1344 end
1345
1346
1347 % --- Executes on button press in pushbutton_plotSoftEntropyConstraint.
1348 function pushbutton_plotSoftEntropyConstraint_Callback(hObject, eventdata, handles)
1349 % hObject    handle to pushbutton_plotSoftEntropyConstraint (see GCBO)
1350 % eventdata  reserved - to be defined in a future version of MATLAB
1351 % handles    structure with handles and user data (see GUIDATA)
1352
1353         create = true;
1354
1355         entropyMenuHandle = handles.popupmenu_entropyConstraintSelector;
1356         entName = getdfName(entropyMenuHandle,'Soft entropy constraint');
1357
1358         if isempty(entName)
1359             create = false;
1360         end
1361
1362         if create == true
1363             % create the history
1364             command = [entName,'.plotDistribution();'];
1365
1366             evalin('base',command);
1367         end
1368
1369 % --- Executes on button press in pushbutton_refreshSoftEntropyConstraintSelector.
1370 function pushbutton_refreshSoftEntropyConstraintSelector_Callback(hObject, eventdata, handles)
1371 % hObject    handle to pushbutton_refreshSoftEntropyConstraintSelector (see GCBO)
1372 % eventdata  reserved - to be defined in a future version of MATLAB
1373 % handles    structure with handles and user data (see GUIDATA)
1374     populateEntropyConstraintList(handles.popupmenu_entropyConstraintSelector);
1375
1376
1377 % --- Executes on button press in pushbutton_createSoftMetaConstraint.
1378 function pushbutton_createSoftMetaConstraint_Callback(hObject, eventdata, handles)
1379 % hObject    handle to pushbutton_createSoftMetaConstraint (see GCBO)
1380 % eventdata  reserved - to be defined in a future version of MATLAB
1381 % handles    structure with handles and user data (see GUIDATA)
1382     createSoftMetaConstraint_Dialog();
1383
1384
1385 % --- Executes on button press in pushbutton_calculateOverlap.
1386 function pushbutton_calculateOverlap_Callback(hObject, eventdata, handles)
1387 % hObject    handle to pushbutton_calculateOverlap (see GCBO)
1388 % eventdata  reserved - to be defined in a future version of MATLAB
1389 % handles    structure with handles and user data (see GUIDATA)
1390     calculateOverlap_Dialog();
1391
1392
1393
1394 % --- Executes on button press in pushbutton_createSoftMatchCorrelConstraint.
1395 function pushbutton_createSoftMatchCorrelConstraint_Callback(hObject, eventdata, handles)
1396 % hObject    handle to pushbutton_createSoftMatchCorrelConstraint (see GCBO)
1397 % eventdata  reserved - to be defined in a future version of MATLAB
1398 % handles    structure with handles and user data (see GUIDATA)
1399     createSoftMatchCorrelDistanceConstraint_Dialog();
1400
1401
1402 % --- Executes on button press in pushbutton_matchCorrel_ztest.
1403 function pushbutton_matchCorrel_ztest_Callback(hObject, eventdata, handles)
1404 % hObject    handle to pushbutton_matchCorrel_ztest (see GCBO)
1405 % eventdata  reserved - to be defined in a future version of MATLAB
1406 % handles    structure with handles and user data (see GUIDATA)
1407         create = true;
1408
1409         sosMenuHandle = handles.popupmenu_SOSSelector;
1410         sosName = getdfName(sosMenuHandle,'SOS');
1411
1412         if isempty(sosName)
1413             create = false;
1414         end
1415
1416         if create == true
1417             createMatchCorrelztest_Dialog();
1418         end
1419
1420
1421 % --- Executes on button press in pushbutton_kstest.
1422 function pushbutton_kstest_Callback(hObject, eventdata, handles)
1423 % hObject    handle to pushbutton_kstest (see GCBO)
1424 % eventdata  reserved - to be defined in a future version of MATLAB
1425 % handles    structure with handles and user data (see GUIDATA)
1426         create = true;
1427
1428         sosMenuHandle = handles.popupmenu_SOSSelector;
1429         sosName = getdfName(sosMenuHandle,'SOS');
1430
1431         if isempty(sosName)
1432             create = false;
1433         end
1434
1435         if create == true
1436             createMatchUniformkstest_Dialog();
1437         end