Description of verbosePrint
Home > src > verbosePrint.m
verbosePrint
PURPOSE
- master print function that regulates cmd line output based on verbosity flags
SYNOPSIS
function verbosePrint(msg,fieldName)
DESCRIPTION
 - master print function that regulates cmd line output based on verbosity flags
 copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
    This file is part of SOS
    SOS is free software: you can redistribute it and/or modify
    it for academic and non-commercial purposes
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.  For commercial or for-profit
    uses, please contact the authors (sos@cnbc.cmu.edu).
    SOS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
CROSS-REFERENCE INFORMATION
This function calls:
initVerbosePrint - initializes the flags which control the verbosity of output
This function is called by:
calculateOverlap_Dialog - calculate overlap dialog
create2samplettest_Dialog - create 2-sample t-test dialog
createHardBoundConstraint_Dialog - create hard bound constraint dialog
createMatchCorrelztest_Dialog - create correlation-matching z-test dialog
createMatchUniformkstest_Dialog - create uniformity ks-test dialog
createPlots_Dialog - create sosplots dialog
createPop_Dialog - create population dialog
createSOS_dialog - create SOS optimizer dialog
createSample_Dialog - create sample dialog
createSingleSampleSoftDistanceConstraint_Dialog - create single sample soft distance constraint dialog
createSoftEntropyConstraint_Dialog - create soft entropy constraint dialog
createSoftMatchCorrelDistanceConstraint_Dialog - create soft match correlation constraint dialog
createSoftMetaConstraint_Dialog - create soft meta-constraint dialog
createTwoSampleSoftDistanceConstraint_Dialog - create two sample soft distance constraint dialog
createsinglesamplettest_Dialog - create single sample t-test dialog
dataFrame - dataframe object
expAnneal - exponentially-decaying temperature annealing object
expAnneal_Dialog - create expAnneal dialog
greedyAnneal - greedy annealing (i.e., T = 0) object
hardBoundConstraint - hard bound constraint object
maxpDecrease_Dialog dialog used for calculating the largest p-decrease value
numSteps_Dialog dialog used to calculate the nubmer of temperature-lowering steps
population - population object
randPopulationAndSampleCandidateSelection - random population and sample selection method for swaps
randPopulationCandidateSelection - random population selection method for selecting swaps
randSampleCandidateSelection - random sample method for selecting swaps
sample - sample object
saveHistory_Dialog - dialog used to save the optimization history
setBufferedHistoryOutfile_Dialog - dialog for setting output file for buffered history output
setSeed - function for setting the seed for the random number generator
setSeed_Dialog - dialog for setting the random seed
softDistanceConstraint - parent class for soft distance constraints
softEntropyConstraint - soft entropy constraint object
softMatchCorrelConstraint - soft correlation matching constraint object
softMetaConstraint - parent class for soft meta-constraints
sos - SOS optimization object
sosCorrelTest - test for equivalence of two correlations
sosHistory - object for storing the detailed history of an optimization
sosPlots - object used to create detailed plots of SOS optimization
sos_gui - sos main GUI
soskstest - object for testing normality using a Kolmogorov-Smirnov test
sosttest - object for creating t-tests
SOURCE CODE
% - master print function that regulates cmd line output based on verbosity flags
%
% copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
%
%    This file is part of SOS
%
%    SOS is free software: you can redistribute it and/or modify
%    it for academic and non-commercial purposes
%    under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.  For commercial or for-profit
%    uses, please contact the authors (sos@cnbc.cmu.edu).
%
%    SOS is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%    You should have received a copy of the GNU General Public License
%    along with SOS (see COPYING.txt).
%    If not, see <http://www.gnu.org/licenses/>.
function verbosePrint(msg,fieldName)
    % the main output driver for SOS information.
    % provides support for displaying data to the standard output.  It's
    % associated functions (e.g., setVerbosePrintVerbosity) can also be
    % used to set what messages will be printed and to what output stream
    % (though only stdout is currently supported).
    %check that what was supplied is a string
    if (ischar(msg) == false)
        error('{msg} supplied to verbosePrint is not a String');
    end
    if (ischar(fieldName) == false)
        error('{fieldName} supplied to verbosePrint is not a String');
    end
    global verbosityFlags;
    if(isempty(verbosityFlags))
        initVerbosePrint();
    end
    %try looking up the string,
    if (isfield(verbosityFlags,fieldName))
        if getfield(verbosityFlags,fieldName) == 1
            disp(msg);
        end
    else
       error('{fieldName} is not a registered verbosityFlag');
    end
end