Description of softDistanceConstraint
Home > src > softDistanceConstraint.m
softDistanceConstraint
PURPOSE
- parent class for soft distance constraints
SYNOPSIS
This is a script file.
DESCRIPTION
 - parent class for soft distance constraints
 copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
    This file is part of SOS
    SOS is free software: you can redistribute it and/or modify
    it for academic and non-commercial purposes
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.  For commercial or for-profit
    uses, please contact the authors (sos@cnbc.cmu.edu).
    SOS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
CROSS-REFERENCE INFORMATION
This function calls:
genericConstraint - parent class for constraints
softConstraint - parent class for soft constraints
softDistanceConstraint - parent class for soft distance constraints
verbosePrint - master print function that regulates cmd line output based on verbosity flags
This function is called by:
genericConstraint - parent class for constraints
softDistanceConstraint - parent class for soft distance constraints
SUBFUNCTIONS
function obj = softDistanceConstraint(varargin)
function obj = construct2SampleSoftDistanceConstraint(obj,varargin)
function obj = construct1SampleSoftDistanceConstraint(obj,varargin)
function cost = initCost(obj)
function swCost = swapCost(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
function obj = initGroupMeans(obj)
function obj = initPairedMeans(obj)
function obj = initGroupStdev(obj)
function obj = initPairedStdev(obj)
function obj = initSingleMeanandTarg(obj)
function obj = initSingleStdevandTarg(obj)
function swGroupMeans(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
function swPairedMeans(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
function swGroupStdev(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
function swPairedStdev(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
function swSingleMean(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
function swSingleStdev(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
function cost = minDiff(obj,x1,x2)
function cost = maxDiff(obj,x1,x2)
function cost = orderedMaxDiff(obj,x1,x2)
function cost = acceptSwap(obj)
function cost = rejectSwap(obj)
function acceptSwapMeans(obj)
function rejectSwapMeans(obj)
function acceptSwapStdev(obj)
function rejectSwapStdev(obj)
function p = softDistanceConstraintInputParser2Sample()
function p = softDistanceConstraintInputParser1Sample()
function p = parse2SampleConstructorArgs(varargin)
function p = parse1SampleConstructorArgs(varargin)
SOURCE CODE
% - parent class for soft distance constraints
%
% copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
%
%    This file is part of SOS
%
%    SOS is free software: you can redistribute it and/or modify
%    it for academic and non-commercial purposes
%    under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.  For commercial or for-profit
%    uses, please contact the authors (sos@cnbc.cmu.edu).
%
%    SOS is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%    You should have received a copy of the GNU General Public License
%    along with SOS (see COPYING.txt).
%    If not, see <http://www.gnu.org/licenses/>.
classdef softDistanceConstraint < softConstraint
    %% creates and supports soft distance constraints
    %
    % This class creates softDistanceConstraint objects that measure the
    % cost (in terms of minimizing or maximizing a distance of a particular stat)
    % associated with the current items in a set, and subsequent to
    % swapping a particular item with another items.
    %
    % Additional functionality and interface requirements are inherited
    % from softConstraint.
    %
    % Currently allows for the following:
    %
    %   min/max/OrderedMax of Group Means, Paired means, Group Stdev,
    %   Paired Stdev, Matching Mean to target, Matching stdev to target
    %
    %
    %PROPERTIES
    %     stat % the statistic to calculate
    %     paired - logical indicating if paired differences or group differences are bieng used
    %     comparison - handle to specific comparison calculator
    %     initStats % handle to global stat initialization method
    %     swStats % handle to local stat update method
    %     acceptsw % handle to local accept swap method
    %     rejectsw % handle to local reject swap method
    %     s1 - sample1
    %     s2 - sample2
    %     s1Col - s1 column index
    %     s2Col - s2 column index
    %     s1ColName - name of column in s1
    %     s2ColName - name of column in s2
    %     stat1 - current stat of sample 1
    %     stat2 - current stat of sample2
    %     swstat1 - stat of sample 1 if swap occurs
    %     swstat2 - stat of sample2 if swap occurs
    %     sumx1sq % sum of the squared values, x, in an array.  Used in stdev calculation
    %     meanx1 % square of the mean value of x in an array.  Used in stdev calculation
    %     swpsumx1sq % swap sum of the squared values, x, in an array.  Used in stdev calculation
    %     swpmeanx1 % swap square of the mean value of x in an array.  Used in stdev calculation
    %     sumx2sq % sum of the squared values, x, in an array.  Used in stdev calculation
    %     meanx2 % square of the mean value of x in an array.  Used in stdev calculation
    %     swpsumx2sq % swap sum of the squared values, x, in an array.  Used in stdev calculation
    %     swpmeanx2 % swap square of the mean value of x in an array.  Used in stdev calculation
    %     targVal % target value to match for 1 sample-to-value matching
    %     zTargVal % normalized target value
    %
    %METHODS
    %   obj =softDistanceConstraint(varargin) - constructor
    %   obj = construct2SampleSoftDistanceConstraint(varargin) % creates a constraint object for cases wehre 2 samples are implicated.
    %   obj = construct1SampleSoftDistanceConstraint(varargin)  % creates a constraint object for cases where 1 sample is implicated.
    %   cost = initCost() - Calculates, saves, and returns the cost value for the currentitems in the sample.
    %   swCost = swapCost(targSample,targSampleIndex, feederdf,feederdfIndex) - Calculates the new cost if items from targSample and feederdf were swapped.
    %   acceptSwap() - updates variables when the proposed swap is accepted
    %   initGroupMeans() - calculates the means of the samples
    %   initPairedMeans() % prepares data for paired mean calculation
    %   initGroupStdev() %calculates the stdevs of the samples
    %   initPairedStdev() % prepares data for paired stdev calculation
    %   initSingleMeanandTarg()  % calculates the mean of the sample1 and sets the target as the target stat
    %   obj = initSingleStdevandtarg(obj) %calculates the stdevs of the samples
    %   swGroupMeans(targSample,targSampleIndex, feederdf,feederdfIndex) - Calculates the new (swap) means if items from targSample and feederd were swapped.
    %   swPairedMeans(targSample,targSampleIndex, feederdf,feederdfIndex) % Calculates the new (swap) means if items from targSample and  feederd were swapped.
    %   swGroupStdev(targSample,targSampleIndex, feederdf,feederdfIndex) % Calculates the new (swap) stdevs if items from targSample and feederd were swapped.
    %   swPairedStdev(targSample,targSampleIndex, feederdf,feederdfIndex) % Calculates the new (swap) stdev if items from targSample and feederdf were swapped.
    %   swSingleMean(targSample,targSampleIndex, feederdf,feederdfIndex) % Calculates the new (swap) mean if items from targSample and  feederd were swapped.
    %   swSingleStdev(targSample,targSampleIndex, feederdf,feederdfIndex)  % Calculates the new (swap) stdevs if items from targSample and feederd were swapped.
    %   cost = minDiff(x1,x2) -  cost function minimized by reduced differences on the statistic
    %   cost = maxDiff(x1,x2) - cost function minimized by maximizing differences on the stat.  Many uses may want to use orderedMaxDiff, instead.
    %   cost = orderedMaxDiff(x1,x2) - cost function minimized by maximizing a difference between the two groups that adheres to s1.stat < s2.stat cost function minimized by reduced differences on the statistic for paired groups
    %   acceptSwapMeans() % updates variables when the proposed swap is accepted for  means
    %   acceptSwapStdev()   % updates variables when the proposed swap is accepted for standard deviations
    %   cost = acceptSwap() % generic reject function
    %   rejectSwapMeans() % updates variables when swap is rejected
    %   rejectSwapStdev()  % updates variables when the proposed swap is rejected
    %
    %METHODS (Static)
    %   p = softDistanceConstraintInputParser2Sample() generates an input parser with parameter / value pairs and validators for the constructor args
    %
    %METHODS (Static, Access = private)
    %   p = parse2SampleConstructorArgs(varargin) - parses the constructor args for cases invovling 2 samples
    %   p = parse1SampleConstructorArgs(varargin)  % parses the constructor args for cases invovling 1 sample
    %% PROPERTIES
    properties
        stat % the statistic to calculate
        paired % logical indicating if paired differences or group differences are bieng used
        comparison % handle to specific comparison calculator
        initStats % handle to global stat initialization method
        swStats % handle to local stat update method
        acceptsw % handle to local accept swap method
        rejectsw % handle to local reject swap method
        s1 % sample1
        s2 % sample2
        s1Col %s1 column index
        s2Col %s2 column index
        s1ColName % name of column in s1
        s2ColName % name of column in s2
        stat1 % current stat of sample 1
        stat2 % current stat of sample2
        swstat1 % stat of sample 1 if swap occurs
        swstat2 % stat of sample2 if swap occurs
        sumx1sq % sum of the squared values, x, in an array.  Used in stdev calculation
        meanx1 % square of the mean value of x in an array.  Used in stdev calculation
        swpsumx1sq % swap sum of the squared values, x, in an array.  Used in stdev calculation
        swpmeanx1 % swap square of the mean value of x in an array.  Used in stdev calculation
        sumx2sq % sum of the squared values, x, in an array.  Used in stdev calculation
        meanx2 % square of the mean value of x in an array.  Used in stdev calculation
        swpsumx2sq % swap sum of the squared values, x, in an array.  Used in stdev calculation
        swpmeanx2 % swap square of the mean value of x in an array.  Used in stdev calculation
        targVal % target value to match for 1 sample-to-value matching
        zTargVal % normalized target value
    end
    methods
        %% softDistanceConstraint CONSTRUCTOR
        function  obj = softDistanceConstraint(varargin)
            % Creates a softDistance Constraint object.  See the
            % constructors for the 2Sample and 1Sample case for additional
            % parameters
            %first, decide what type of object to create.  This will be
            %based on whether the desired function involves 2 means, or 1.
            p = inputParser;
            p.addParamValue('fnc','null', ...
                 @(fnc)any(strcmp({'min', 'max','orderedMax','match1SampleVal'},fnc)));
            p.KeepUnmatched = true;
            p.parse(varargin{:});
            %cases involving 2 samples
            if any([strcmp(p.Results.fnc,'min'), ...
                    strcmp(p.Results.fnc,'max'), ...
                    strcmp(p.Results.fnc,'orderedMax')])
                obj = construct2SampleSoftDistanceConstraint(obj,varargin);
            % cases invovling 1 sample matched to a value
            elseif any(strcmp(p.Results.fnc,'match1SampleVal'))
                obj = construct1SampleSoftDistanceConstraint(obj,varargin);
            else
                error(['Could not create a soft constraint with <fnc>: ', ...
                        p.Results.fnc]);
            end
            obj.cost = NaN;
            obj.swCost = NaN;
            verbosePrint('Soft Distance Constraint has been created', ...
                    'softDistanceConstraint_Constructor_endObjCreation');
        end % constructor
        %% obj = construct2SampleSoftDistanceConstraint(varargin) METHOD
        function obj = construct2SampleSoftDistanceConstraint(obj,varargin)
            % creates a constraint object for cases where 2 samples are implicated.
            % CONSTRUCTOR - Creates a softDistanceConstraint object
            %
            % CALL:
            % softDistanceConstraint(varargin<defined below>)
            %
            % PARAMETERS:
            % REQUIRED:
            %   'sosObj'/sos object - the SOS object the constraint will be linked to, and which contains the samples the constraint operates on.
            %   'constraintType'/'soft' - the type of contraint - must be 'soft'
            %   'fnc'/'min'|'max'|'orderedMax' the distance function to create.  If orderedMax, s1 < s2 on the specified dimension
            %   'stat'/'mean'|'stdev' - the statistic to calculate the difference on
            %   'sample1'/sample - the first sample
            %   'sample2'/sample - the second sample
            %   's1ColName'/string - name of column in 1st sample
            %   's2ColName'/string - name of column in 2nd sample
            %   'paired'/logical - should pairwise or group level distances be calculated
            % OPTIONAL:
            %   'exponent'/numeric - defaults to 2 (quadratic difference)
            %   'weight'/numeric - defaults to 1 (equal weighting of all soft costs)
            %
            % EXAMPLE:
            % mySOS.addConstraint('sosObj',mySOS,'constraintType','soft', ...
            %   'fnc','min','stat','mean','sample1',s1,'sample2',s2,'s1ColName','Lg10WF', ...
            %   's2ColName','Lg10WF','exponent',2,'paired',false,'weight', 1);
            p = softDistanceConstraint.parse2SampleConstructorArgs(varargin{:});
            if(p.Results.sosObj.containsSample(p.Results.sample1) == false)
                error('Cannot create soft distance constraint: sos Object does not contain the sample1');
            end
            if(p.Results.sosObj.containsSample(p.Results.sample2) == false)
                error('Cannot create soft distance constraint: sos Object does not contain sample2');
            end
            col1 = p.Results.sample1.colName2colNum(p.Results.s1ColName);
            if(col1 == -1)
                error('Specified column name not found in sample1');
            end
            if(strcmp(p.Results.sample1.format{col1},'%f') == 0)
                error('Specified column is not of numeric (%f) format, so cannot use as hard bound');
            end
            col2 = p.Results.sample2.colName2colNum(p.Results.s2ColName);
            if(col2 == -1)
                error('Specified column name not found in sample');
            end
            if(strcmp(p.Results.sample2.format{col2},'%f') == 0)
                error('Specified column is not of numeric (%f) format, so cannot use as hard bound; 2nd sample');
            end
            %if the lengths are not going to be identical, do not run the
            %test if it is paired.  The init and swap methods will ensure
            %that if practically the data are NaN, the optimization will
            %stop.
            if(p.Results.paired == true)
                if length(p.Results.sample1.n) ~= length(p.Results.sample2.n)
                    error('Sample sizes must be equal if using paired matching');
                end
            end
            % Assign the comparison function appropriate for the constraint
            if(p.Results.paired ~= true & p.Results.paired ~= false)
                error('<paired> parameter must be either true/false (1/0)');
            end
            %ASSIGN HANDLE TO STAT CALCULATION METHOD
            if(strcmp(p.Results.stat,'mean') && p.Results.paired == false)
                obj.initStats = @obj.initGroupMeans;
                obj.swStats = @obj.swGroupMeans;
                obj.acceptsw = @obj.acceptSwapMeans;
                obj.rejectsw = @obj.rejectSwapMeans;
            elseif(strcmp(p.Results.stat,'mean') && p.Results.paired == true)
                obj.initStats = @obj.initPairedMeans;
                obj.swStats = @obj.swPairedMeans;
                obj.acceptsw = @obj.acceptSwapMeans;
                obj.rejectsw = @obj.rejectSwapMeans;
            elseif(strcmp(p.Results.stat,'stdev')  && p.Results.paired == false)
                obj.initStats = @obj.initGroupStdev;
                obj.swStats = @obj.swGroupStdev;
                obj.acceptsw = @obj.acceptSwapStdev;
                obj.rejectsw = @obj.rejectSwapStdev;
            elseif(strcmp(p.Results.stat,'stdev')  && p.Results.paired == true)
                obj.initStats = @obj.initPairedStdev;
                obj.swStats = @obj.swPairedStdev;
                obj.acceptsw = @obj.acceptSwapStdev;
                obj.rejectsw = @obj.rejectSwapStdev;
            else
               error('function not yet supported');
            end
            % ASSIGN HANDLE TO DIFFERENCE COMPARISON METHOD
            % Group differences:
            if(strcmp(p.Results.fnc,'min'))
                obj.comparison = @obj.minDiff;
            elseif(strcmp(p.Results.fnc,'max'))
                obj.comparison = @obj.maxDiff;
            elseif(strcmp(p.Results.fnc,'orderedMax'))
                obj.comparison = @obj.orderedMaxDiff;
            else
                error('function not yet supported');
            end
            % parent properties
            obj.sosObj = p.Results.sosObj;
            obj.constraintType = p.Results.constraintType;
            obj.fnc = p.Results.fnc;
            obj.weight = p.Results.weight;
            obj.exp = p.Results.exponent;
            obj.stat = p.Results.stat;
            obj.s1 = p.Results.sample1;
            obj.s2 = p.Results.sample2;
            obj.s1Col = col1;
            obj.s2Col = col2;
            obj.s1ColName = p.Results.s1ColName;
            obj.s2ColName = p.Results.s2ColName;
            obj.paired = p.Results.paired;
            % add the name and the label
            obj.label = [obj.constraintType,'_',obj.fnc,'_',...
                    obj.stat,'_',...
                    obj.s1.name,'_',obj.s1ColName,'_',...
                    obj.s2.name,'_',obj.s2ColName,'_',...
                    'p',num2str(obj.paired)','_w',...
                    num2str(obj.weight),'_e',num2str(obj.exp)];
            if any(strcmp(p.UsingDefaults,'name'))
                obj.name = obj.label;
            else
                 obj.name = p.Results.name;
            end
        end %construct2SampleSoftDistanceConstraint
        %% obj = construct1SampleSoftDistanceConstraint(varargin) METHOD
        function obj = construct1SampleSoftDistanceConstraint(obj,varargin)
            % creates a constraint object for cases where 1 sample is implicated.
            % CONSTRUCTOR - Creates a softDistanceConstraint object
            %
            % CALL:
            % softDistanceConstraint(varargin<defined below>)
            %
            % PARAMETERS:
            % REQUIRED:
            %   'sosObj'/sos object - the SOS object the constraint will be linked to, and which contains the samples the constraint operates on.
            %   'constraintType'/'soft' - the type of contraint - must be 'soft'
            %   'fnc'/'match1SampleVal' the distance function to create.  If orderedMax, s1 < s2 on the specified dimension
            %   'stat'/'mean'|'stdev' - the statistic to calculate the difference on
            %   'sample1'/sample - the first sample
            %   's1ColName'/string - name of column in 1st sample
            % OPTIONAL:
            %   'exponent'/numeric - defaults to 2 (quadratic difference)
            %   'weight'/numeric - defaults to 1 (equal weighting of all soft costs)
            %   'targVal'/numeric - value to match the stat to.
            %
            p = softDistanceConstraint.parse1SampleConstructorArgs(varargin{:});
            if(p.Results.sosObj.containsSample(p.Results.sample1) == false)
                error('Cannot create soft distance constraint: sos Object does not contain the sample1');
            end
            col1 = p.Results.sample1.colName2colNum(p.Results.s1ColName);
            if(col1 == -1)
                error('Specified column name not found in sample1');
            end
            if(strcmp(p.Results.sample1.format{col1},'%f') == 0)
                error('Specified column is not of numeric (%f) format, so cannot use as hard bound');
            end
            % Assign the comparison function appropriate for the constraint
            %ASSIGN HANDLE TO STAT CALCULATION METHOD
            if(strcmp(p.Results.stat,'mean'))
                obj.initStats = @obj.initSingleMeanandTarg;
                obj.swStats = @obj.swSingleMean;
                obj.acceptsw = @obj.acceptSwapMeans;
                obj.rejectsw = @obj.rejectSwapMeans;
                obj.comparison = @obj.minDiff;
            elseif(strcmp(p.Results.stat,'stdev'))
                obj.initStats = @obj.initSingleStdevandTarg;
                obj.swStats = @obj.swSingleStdev;
                obj.acceptsw = @obj.acceptSwapStdev;
                obj.rejectsw = @obj.rejectSwapStdev;
                obj.comparison = @obj.minDiff;
            else
               error('function not yet supported');
            end
            %Finally, need to convert the raw value supplied by the user
            %into the standardized value used for comparison purposes.  We
            %do this by conslulting the SOS object's normalization data.
            %find the normalization params for this data column:
            obj.targVal = p.Results.targVal;
            obj.zTargVal = NaN;
            % parent properties
            obj.sosObj = p.Results.sosObj;
            obj.constraintType = p.Results.constraintType;
            obj.fnc = p.Results.fnc;
            obj.weight = p.Results.weight;
            obj.stat = p.Results.stat;
            obj.s1 = p.Results.sample1;
            obj.s1Col = col1;
            obj.s2 = NaN;
            obj.s1ColName = p.Results.s1ColName;
            obj.exp = p.Results.exponent;
            % add the name and the label
            obj.label = [obj.constraintType,'_',obj.fnc,'_',...
                    obj.stat,'_',num2str(obj.targVal),'_',obj.s1.name,'_',...
                    obj.s1ColName,'_w',...
                    num2str(obj.weight),'_e',num2str(obj.exp)];
            if any(strcmp(p.UsingDefaults,'name'))
                obj.name = obj.label;
            else
                 obj.name = p.Results.name;
            end
        end %construct1SampleSoftDistanceConstraint
        %% cost = initCost() METHOD
        function cost = initCost(obj)
            % Calculates, saves, and returns the cost value for the current items in the sample.
            %
            %CALL:
            %   <softDistanceConstraint>.initCost();
            %
            %SYNOPSIS:
            % Calculates the cost for the current items in the sample based
            % on the specified constraint.  This calculation is done on the
            % global dataset, rather than using the differential local
            % computation used when calculating swap costs.
            %
            %init the stats, then compare them.  Return the calculated cost
            obj = obj.initStats();
            cost = obj.comparison(obj.stat1,obj.stat2);
            obj.swstat1 = NaN;
            obj.swstat2 = NaN;
            obj.cost = cost;
            obj.swCost = NaN;
        end
        %%  swCost(targSample,targSampleIndex, feederdf,feederdfIndex) FUNCTION
        function swCost = swapCost(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
            % Calculates the new cost if items from targSample and feederdf were swapped.
            %
            %By definition, if this method is called it means that at least
            % one of the two swap objects is implicated in this function
            %
            %PARAMETERS:
            %   targSample - the target sample (i.e., the object that will call it's swapSample() method if a swap later occurs).
            %   targSampleIndex - row index of item to swap
            %   feederdf - dataframe (sample/pop) containin the other item to swap
            %   feederdfIndex - row index of item to swap.
           if (obj.s1 ~= targSample && obj.s2 ~= targSample ...
                   && obj.s1 ~= feederdf && obj.s2  ~= feederdf)
               error('swCost called, but no sample part of this cost function');
           end
           % update the stats, then calculate cost of new stats
           obj.swStats(targSample,targSampleIndex, feederdf,feederdfIndex);
            swCost = obj.comparison(obj.swstat1,obj.swstat2);
            obj.swCost = swCost;
        end
        %% initGroupMeans() METHOD
        function obj = initGroupMeans(obj)
            % calculates the means of the samples
            obj.stat1= mean(obj.s1.zdata{obj.s1Col});
            obj.stat2= mean(obj.s2.zdata{obj.s2Col});
            if isnan(obj.stat1) || isnan(obj.stat2)
                error('NaN obtained during initstat computation (perhaps there is missing data for an item?)');
            end
        end
        %% initPairedMeans() METHOD
        function obj = initPairedMeans(obj)
            % prepares data for paired mean calculation
            % make sure there are no nan's.
            if (any(isnan(obj.s1.zdata{obj.s1Col})))
                error('NaN obtained during initstat computation of sample 1 (perhaps there is missing data for an item?)');
            elseif (any(isnan(obj.s2.zdata{obj.s2Col})))
                error('NaN obtained during initstat computation of sample 2 (perhaps there is missing data for an item?)');
            end
            % calculate the statistic.  In contrast to the group mean
            % statistic, here we'll calculate the difference in each pair
            % of observations and sum that in stat2, and leave stat1  ==0
            tmpstat2 = 0;
            for i=1:obj.s1.n
                x = obj.s2.zdata{obj.s2Col}(i) - obj.s1.zdata{obj.s1Col}(i);
                % when trying to minimize, any difference, in either
                % direction, is bad.  When trying to maximize, then let the
                % sign enter into the equation.
                if strcmp(obj.fnc,'min')
                    x = abs(x);
                end
                 tmpstat2 = tmpstat2 + x;
            end
            % calculate the mean of x
            obj.stat2 = tmpstat2/obj.s1.n;
            obj.stat1 = 0; % always relative to no difference
        end
        %% initStdev(obj) METHOD
        function obj = initGroupStdev(obj)
            %calculates the stdevs of the samples
            obj.sumx1sq = sum((obj.s1.zdata{obj.s1Col}).^2);
            obj.meanx1 = mean(obj.s1.zdata{obj.s1Col});
            n1 = length(obj.s1.zdata{obj.s1Col});
            %use the computational formula to efficiently calculate the sum
            stdevx1 = (1/(n1-1) * obj.sumx1sq ...
                        - n1/(n1-1) * obj.meanx1^2)^0.5;
            obj.sumx2sq = sum((obj.s2.zdata{obj.s2Col}).^2);
            obj.meanx2 = mean(obj.s2.zdata{obj.s2Col});
            n2 = length(obj.s2.zdata{obj.s2Col});
            %use the computational formula to efficiently calculate the sum
            stdevx2 = (1/(n2-1) * obj.sumx2sq ...
                        - n2/(n2-1) * obj.meanx2^2)^0.5;
            obj.stat1 = stdevx1;
            obj.stat2 = stdevx2;
            if isnan(obj.stat1) || isnan(obj.stat2)
                error('NaN obtained during initstat computation (perhaps there is missing data for an item?)');
            end
        end
        %% initPairedMeans() METHOD
        function obj = initPairedStdev(obj)
            % prepares data for paired mean calculation
            % make sure there are no nan's.
            if (any(isnan(obj.s1.zdata{obj.s1Col})))
                error('NaN obtained during initstat computation of sample 1 (perhaps there is missing data for an item?)');
            elseif (any(isnan(obj.s2.zdata{obj.s2Col})))
                error('NaN obtained during initstat computation of sample 2 (perhaps there is missing data for an item?)');
            end
            % calculate the statistic.  In contrast to the group mean
            % statistic, here we'll calculate the difference in each pair
            % of observations and sum that in stat2, and leave stat1  ==0
            obj.sumx2sq = 0;
            obj.meanx2 = 0;
            n = length(obj.s2.zdata{obj.s2Col});
            for i=1:n
                x = obj.s2.zdata{obj.s2Col}(i) - obj.s1.zdata{obj.s1Col}(i);
                obj.sumx2sq = obj.sumx2sq + x^2;
                obj.meanx2 = obj.meanx2 + x/n;
            end
            %use the computational formula to efficiently calculate the sum
            stdevx2 = (1/(n-1) * obj.sumx2sq ...
                        - n/(n-1) * obj.meanx2^2)^0.5;
            % calculate the mean of x
            obj.stat2 = stdevx2;
            obj.stat1 = 0; % always relative to no difference
        end
        %% initSingleMeanandTarg() METHOD
        function obj = initSingleMeanandTarg(obj)
            % calculates the mean of the sample1 and sets the target as the target stat
            obj.stat2= mean(obj.s1.zdata{obj.s1Col});
             %normalize the target value to match against
            targCol = obj.sosObj.allData.colName2colNum(obj.s1ColName);
            if(targCol == -1)
                error('Normalized data for this value may not yet exist (try normalizing first)');
            end
            obj.zTargVal = (obj.targVal - obj.sosObj.allDataColMean(targCol)) ...
                            / obj.sosObj.allDataColStd(targCol);
           obj.stat1 = obj.zTargVal;
            if isnan(obj.stat1) || isnan(obj.stat2)
                error('NaN obtained during initstat computation (perhaps there is missing data for an item?)');
            end
        end
        %% initSingleStdevandtarg(obj) METHOD
        function obj = initSingleStdevandTarg(obj)
            %calculates the stdevs of the samples
            obj.sumx2sq = sum((obj.s1.zdata{obj.s1Col}).^2);
            obj.meanx2 = mean(obj.s1.zdata{obj.s1Col});
            n2 = length(obj.s1.zdata{obj.s1Col});
            %use the computational formula to efficiently calculate the sum
            stdevx2 = (1/(n2-1) * obj.sumx2sq ...
                        - n2/(n2-1) * obj.meanx2^2)^0.5;
            obj.stat2 = stdevx2;
             %normalize the target value to match against
            targCol = obj.sosObj.allData.colName2colNum(obj.s1ColName);
            if(targCol == -1)
                error('Normalized data for this value may not yet exist (try normalizing first)');
            end
            obj.zTargVal = (obj.targVal) ...
                            / obj.sosObj.allDataColStd(targCol);
            obj.stat1 = obj.zTargVal;
            if isnan(obj.stat1) || isnan(obj.stat2)
                error('NaN obtained during initstat computation (perhaps there is missing data for an item?)');
            end
        end
        %% swGroupMeans(targSample,targSampleIndex,feederdf,feederdfIndex) FUNCTION
        function swGroupMeans(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
           % Calculates the new (swap) means if items from targSample and feederd were swapped.
           %
           % Inputs are the same as for swapCost()
           tempswm1 = obj.stat1;
           tempswm2 = obj.stat2;
            %do the adjustments of the means
            %basic idea is to take out the old value from that mean and
            %then put in the new one.  Do that seperately for each
            %dataframe to cover all eventualities (i.e., if either
            %targSample or feederdf, or both, are part of the current cost
            %function.
            if targSample == obj.s1
                tempswm1 = tempswm1 - (targSample.zdata{obj.s1Col}(targSampleIndex)/length(targSample.zdata{obj.s1Col}));
                tempswm1 = tempswm1 + (feederdf.zdata{obj.s1Col}(feederdfIndex)/length(targSample.zdata{obj.s1Col}));
            elseif targSample == obj.s2
                tempswm2 = tempswm2 - (targSample.zdata{obj.s2Col}(targSampleIndex)/length(targSample.zdata{obj.s2Col}));
                tempswm2 = tempswm2 + (feederdf.zdata{obj.s2Col}(feederdfIndex)/length(targSample.zdata{obj.s2Col}));
            end
            if feederdf == obj.s1
                tempswm1 = tempswm1 - (feederdf.zdata{obj.s1Col}(feederdfIndex)/length(feederdf.zdata{obj.s1Col}));
                tempswm1 = tempswm1 + (targSample.zdata{obj.s1Col}(targSampleIndex)/length(feederdf.zdata{obj.s1Col}));
            elseif feederdf == obj.s2
                tempswm2 = tempswm2 - (feederdf.zdata{obj.s2Col}(feederdfIndex)/length(feederdf.zdata{obj.s2Col}));
                tempswm2 = tempswm2 + (targSample.zdata{obj.s2Col}(targSampleIndex)/length(feederdf.zdata{obj.s2Col}));
            end
            obj.swstat1 = tempswm1;
            obj.swstat2 = tempswm2;
            if isnan(obj.swstat1) || isnan(obj.swstat2)
                error('NaN obtained during swstat computation (perhaps there is missing data for an item?)');
            end
        end
        %% swPairedMeans(targSample,targSampleIndex,feederdf,feederdfIndex) FUNCTION
        function swPairedMeans(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
           % Calculates the new (swap) means if items from targSample and feederd were swapped.
           %
           % Inputs are the same as for swapCost()
           tempswm2 = obj.stat2;
           %tempswm2 should remain 0 at all times
            %do the adjustments of the means
            %basic idea is to take out the old value from that mean and
            %then put in the new one.  Do that seperately for each
            %dataframe to cover all eventualities (i.e., if either
            %targSample or feederdf, or both, are part of the current cost
            %function.
            nobs = length(obj.s1.zdata{obj.s1Col});
            if targSample == obj.s1
                %take the existing contribution to the stat due to the data
                %out.
                curx = (obj.s2.zdata{obj.s2Col}(targSampleIndex) - ...
                        targSample.zdata{obj.s1Col}(targSampleIndex))/nobs;
                if strcmp(obj.fnc,'min')
                    curx = abs(curx);
                end
                tempswm2 = tempswm2 - curx;
                %add in the new value
                newx = (obj.s2.zdata{obj.s2Col}(targSampleIndex) - ...
                          feederdf.zdata{obj.s1Col}(feederdfIndex)) / nobs;
                if strcmp(obj.fnc,'min')
                    newx = abs(newx);
                end
                tempswm2 = tempswm2 + newx;
                % update is complete
            elseif targSample == obj.s2
                curx  = (targSample.zdata{obj.s2Col}(targSampleIndex) - ...
                            obj.s1.zdata{obj.s1Col}(targSampleIndex))/nobs;
                if strcmp(obj.fnc,'min')
                    curx = abs(curx);
                end
                tempswm2 = tempswm2 - curx;
                newx = (feederdf.zdata{obj.s2Col}(feederdfIndex) - ...
                        obj.s1.zdata{obj.s1Col}(targSampleIndex))/nobs;
                if strcmp(obj.fnc,'min')
                    newx = abs(newx);
                end
                tempswm2 = tempswm2 + newx;
            end
            if feederdf == obj.s1
                curx = (obj.s2.zdata{obj.s2Col}(feederdfIndex) - ...
                          feederdf.zdata{obj.s1Col}(feederdfIndex)) / nobs;
                if strcmp(obj.fnc,'min')
                    curx = abs(curx);
                end
                tempswm2 = tempswm2 - curx;
                newx = (obj.s2.zdata{obj.s2Col}(feederdfIndex) - ...
                        targSample.zdata{obj.s1Col}(targSampleIndex))/nobs;
                 if strcmp(obj.fnc,'min')
                    newx = abs(newx);
                end
                tempswm2 = tempswm2 + newx;
            elseif feederdf == obj.s2
                curx = (feederdf.zdata{obj.s2Col}(feederdfIndex) - ...
                        obj.s1.zdata{obj.s1Col}(feederdfIndex))/nobs;
                if strcmp(obj.fnc,'min')
                    curx = abs(curx);
                end
                tempswm2 = tempswm2 - curx;
                newx = (targSample.zdata{obj.s2Col}(targSampleIndex) - ...
                            obj.s1.zdata{obj.s1Col}(feederdfIndex))/nobs;
                if strcmp(obj.fnc,'min')
                    newx = abs(newx);
                end
                tempswm2 = tempswm2 + newx;
            end
            obj.swstat2 = tempswm2;
            obj.swstat1 = obj.stat1; % again, just copy the zero over
            if isnan(obj.swstat1)
                error('NaN obtained during swstat computation (perhaps there is missing data for an item?)');
            end
        end %swPairedMeans
        %% swGroupStdev(targSample,targSampleIndex, feederdf,feederdfIndex)
        function swGroupStdev(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
           % Calculates the new (swap) stdevs if items from targSample and feederd were swapped.
           %
           % Inputs are the same as for swapCost()
            n1 = length(obj.s1.zdata{obj.s1Col});
            n2 = length(obj.s2.zdata{obj.s2Col});
            obj.swpsumx1sq = obj.sumx1sq;
            obj.swpmeanx1 = obj.meanx1;
            obj.swpsumx2sq = obj.sumx2sq;
            obj.swpmeanx2 = obj.meanx2;
            if targSample == obj.s1
                %must update 2 params %first, take out the old observation, then add in thew new
                obj.swpsumx1sq = obj.swpsumx1sq - (targSample.zdata{obj.s1Col}(targSampleIndex))^2;
                obj.swpmeanx1 = obj.swpmeanx1 - (targSample.zdata{obj.s1Col}(targSampleIndex))/n1;
                obj.swpsumx1sq = obj.swpsumx1sq + (feederdf.zdata{obj.s1Col}(feederdfIndex))^2;
                obj.swpmeanx1 = obj.swpmeanx1 + (feederdf.zdata{obj.s1Col}(feederdfIndex))/n1;
            elseif targSample == obj.s2
                obj.swpsumx2sq = obj.swpsumx2sq - (targSample.zdata{obj.s2Col}(targSampleIndex))^2;
                obj.swpmeanx2 = obj.swpmeanx2 - (targSample.zdata{obj.s2Col}(targSampleIndex))/n2;
                obj.swpsumx2sq = obj.swpsumx2sq + (feederdf.zdata{obj.s2Col}(feederdfIndex))^2;
                obj.swpmeanx2 = obj.swpmeanx2 + (feederdf.zdata{obj.s2Col}(feederdfIndex))/n2;
            end
            if feederdf == obj.s1
                obj.swpsumx1sq = obj.swpsumx1sq -  (feederdf.zdata{obj.s1Col}(feederdfIndex))^2;
                obj.swpmeanx1 = obj.swpmeanx1 - (feederdf.zdata{obj.s1Col}(feederdfIndex))/n1;
                obj.swpsumx1sq = obj.swpsumx1sq + (targSample.zdata{obj.s1Col}(targSampleIndex))^2;
                obj.swpmeanx1 = obj.swpmeanx1 + (targSample.zdata{obj.s1Col}(targSampleIndex))/n1;
            elseif feederdf == obj.s2
                obj.swpsumx2sq = obj.swpsumx2sq -  (feederdf.zdata{obj.s2Col}(feederdfIndex))^2;
                obj.swpmeanx2 = obj.swpmeanx2 - (feederdf.zdata{obj.s2Col}(feederdfIndex))/n2;
                obj.swpsumx2sq = obj.swpsumx2sq + (targSample.zdata{obj.s2Col}(targSampleIndex))^2;
                obj.swpmeanx2 = obj.swpmeanx2 + (targSample.zdata{obj.s2Col}(targSampleIndex))/n2;
            end
            stdevx1 = (1/(n1-1) * obj.swpsumx1sq ...
                        - n1/(n1-1) * obj.swpmeanx1^2)^0.5;
            stdevx2 = (1/(n2-1) * obj.swpsumx2sq ...
                        - n2/(n2-1) * obj.swpmeanx2^2)^0.5;
            obj.swstat1 = stdevx1;
            obj.swstat2 = stdevx2;
            if isnan(obj.swstat1) || isnan(obj.swstat2)
                error('NaN obtained during swstat computation (perhaps there is missing data for an item?)');
            end
        end
        %% swPairedStdev(targSample,targSampleIndex,feederdf,feederdfIndex) FUNCTION
        function swPairedStdev(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
           % Calculates the new (swap) stdev if items from targSample and feederd were swapped.
           %
           %NOTE: When repeated tens of thousands of times, this manner of
           %updated std via local difference calculations tends to lead to
           %some very small imprecisions relative to re-calculating the
           %actual values from scratch.  These deviations appear to be
           %trivially small in all cases examined to date though.  This
           %fact is mentioned here presently only because the
           %detail-oriented individual may find values like  0.00000001
           %instead of 0, which nevertheless
           %likely will have no practical consequence
           %for the matching algorithm.
           %
           % Inputs are the same as for swapCost()
            obj.swpsumx2sq = obj.sumx2sq;
            obj.swpmeanx2 = obj.meanx2;
            n = length(obj.s1.zdata{obj.s1Col});
            if targSample == obj.s1
                %take the existing contribution to the stat due to the data
                %out.
                curx = (obj.s2.zdata{obj.s2Col}(targSampleIndex) - ...
                        targSample.zdata{obj.s1Col}(targSampleIndex));
                obj.swpsumx2sq = obj.swpsumx2sq - curx^2;
                obj.swpmeanx2 = obj.swpmeanx2 - curx/n;
                %add in the new value
                newx = (obj.s2.zdata{obj.s2Col}(targSampleIndex) - ...
                          feederdf.zdata{obj.s1Col}(feederdfIndex));
                obj.swpsumx2sq = obj.swpsumx2sq + newx^2;
                obj.swpmeanx2 = obj.swpmeanx2 + newx/n;
                % update is complete
            elseif targSample == obj.s2
                curx  = (targSample.zdata{obj.s2Col}(targSampleIndex) - ...
                            obj.s1.zdata{obj.s1Col}(targSampleIndex));
                obj.swpsumx2sq = obj.swpsumx2sq - curx^2;
                obj.swpmeanx2 = obj.swpmeanx2 - curx/n;
                newx = (feederdf.zdata{obj.s2Col}(feederdfIndex) - ...
                        obj.s1.zdata{obj.s1Col}(targSampleIndex));
                obj.swpsumx2sq = obj.swpsumx2sq + newx^2;
                obj.swpmeanx2 = obj.swpmeanx2 + newx/n;
            end
            if feederdf == obj.s1
                curx = (obj.s2.zdata{obj.s2Col}(feederdfIndex) - ...
                          feederdf.zdata{obj.s1Col}(feederdfIndex));
                obj.swpsumx2sq = obj.swpsumx2sq - curx^2;
                obj.swpmeanx2 = obj.swpmeanx2 - curx/n;
                newx = (obj.s2.zdata{obj.s2Col}(feederdfIndex) - ...
                        targSample.zdata{obj.s1Col}(targSampleIndex));
                obj.swpsumx2sq = obj.swpsumx2sq + newx^2;
                obj.swpmeanx2 = obj.swpmeanx2 + newx/n;
            elseif feederdf == obj.s2
                curx = (feederdf.zdata{obj.s2Col}(feederdfIndex) - ...
                        obj.s1.zdata{obj.s1Col}(feederdfIndex));
                obj.swpsumx2sq = obj.swpsumx2sq - curx^2;
                obj.swpmeanx2 = obj.swpmeanx2 - curx/n;
                newx = (targSample.zdata{obj.s2Col}(targSampleIndex) - ...
                            obj.s1.zdata{obj.s1Col}(feederdfIndex));
                obj.swpsumx2sq = obj.swpsumx2sq + newx^2;
                obj.swpmeanx2 = obj.swpmeanx2 + newx/n;
            end
            % Special override:
            % if it happens that targSample and feederdf both correspond to
            % the samples for which stdev is being calculated, and that
            % the exact same item is being swapped out in both cases, the
            % swpsumx2sq should not change because the two swaps should
            % cancel each other out.  However, in the current
            % implementation this doesn't happen and instead we get 2x the
            % negative subtraction because the second calculation is not
            % aware of the shifts completed in the first.  This can,
            % however, be fixed in the present case quite simply by not
            % changing swpsumx2sq in this specific instance.  This only
            % happens in this case because the squaring of the terms leads
            % to the sign of the calculation being ignored, and as such the
            % calculation of swap means should not suffer in the same
            % fashion.
            if((targSample == obj.s1 || targSample == obj.s2) && ...
                    (feederdf == obj.s1 || feederdf == obj.s2) && ...
                targSampleIndex == feederdfIndex)
                obj.swpsumx2sq = obj.sumx2sq;
            end
            % calculate the updated stdev:
           %use the computational formula to efficiently calculate the sum
            swpstdevx2 = (1/(n-1) * obj.swpsumx2sq ...
                        - n/(n-1) * obj.swpmeanx2^2)^0.5;
            obj.swstat2 = swpstdevx2;
            obj.swstat1 = obj.stat1; % again, just copy the zero over
            if isnan(obj.swstat1)
                error('NaN obtained during swstat computation (perhaps there is missing data for an item?)');
            end
        end %swPairedStdev
        %% swSingleMean(targSample,targSampleIndex,feederdf,feederdfIndex) METHOD
        function swSingleMean(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
           % Calculates the new (swap) mean if items from targSample and feederd were swapped.
           %
           % Inputs are the same as for swapCost()
           tempswm2 = obj.stat2;
            %do the adjustments of the means
            %basic idea is to take out the old value from that mean and
            %then put in the new one.  Do that seperately for each
            %dataframe to cover all eventualities (i.e., if either
            %targSample or feederdf, or both, are part of the current cost
            %function.
            if targSample == obj.s1
                tempswm2 = tempswm2 - (targSample.zdata{obj.s1Col}(targSampleIndex)/length(targSample.zdata{obj.s1Col}));
                tempswm2 = tempswm2 + (feederdf.zdata{obj.s1Col}(feederdfIndex)/length(targSample.zdata{obj.s1Col}));
            end
1000             if feederdf == obj.s1
1001                 tempswm2 = tempswm2 - (feederdf.zdata{obj.s1Col}(feederdfIndex)/length(feederdf.zdata{obj.s1Col}));
1002                 tempswm2 = tempswm2 + (targSample.zdata{obj.s1Col}(targSampleIndex)/length(feederdf.zdata{obj.s1Col}));
1003             end
1004
1005             obj.swstat2 = tempswm2;
1006             obj.swstat1 = obj.stat1;
1007
1008             if isnan(obj.swstat1) || isnan(obj.swstat2)
1009                 error('NaN obtained during swstat computation (perhaps there is missing data for an item?)');
1010             end
1011         end
1012
1013         %% swSingleStdev(targSample,targSampleIndex, feederdf,feederdfIndex)
1014         function swSingleStdev(obj,targSample,targSampleIndex, feederdf,feederdfIndex)
1015            % Calculates the new (swap) stdevs if items from targSample and feederd were swapped.
1016            %
1017            % Inputs are the same as for swapCost()
1018
1019             n2 = length(obj.s1.zdata{obj.s1Col});
1020
1021             obj.swpsumx2sq = obj.sumx2sq;
1022             obj.swpmeanx2 = obj.meanx2;
1023
1024             if targSample == obj.s1
1025                 %must update 2 params %first, take out the old observation, then add in thew new
1026                 obj.swpsumx2sq = obj.swpsumx2sq - (targSample.zdata{obj.s1Col}(targSampleIndex))^2;
1027                 obj.swpmeanx2 = obj.swpmeanx2 - (targSample.zdata{obj.s1Col}(targSampleIndex))/n2;
1028                 obj.swpsumx2sq = obj.swpsumx2sq + (feederdf.zdata{obj.s1Col}(feederdfIndex))^2;
1029                 obj.swpmeanx2 = obj.swpmeanx2 + (feederdf.zdata{obj.s1Col}(feederdfIndex))/n2;
1030             end
1031
1032             if feederdf == obj.s1
1033                 obj.swpsumx2sq = obj.swpsumx2sq -  (feederdf.zdata{obj.s1Col}(feederdfIndex))^2;
1034                 obj.swpmeanx2 = obj.swpmeanx2 - (feederdf.zdata{obj.s1Col}(feederdfIndex))/n2;
1035                 obj.swpsumx2sq = obj.swpsumx2sq + (targSample.zdata{obj.s1Col}(targSampleIndex))^2;
1036                 obj.swpmeanx2 = obj.swpmeanx2 + (targSample.zdata{obj.s1Col}(targSampleIndex))/n2;
1037             end
1038
1039             stdevx2 = (1/(n2-1) * obj.swpsumx2sq ...
1040                         - n2/(n2-1) * obj.swpmeanx2^2)^0.5;
1041
1042             obj.swstat1 = obj.stat1; %just copy over the target
1043             obj.swstat2 = stdevx2;
1044
1045             if isnan(obj.swstat1) || isnan(obj.swstat2)
1046                 error('NaN obtained during swstat computation (perhaps there is missing data for an item?)');
1047             end
1048
1049         end
1050
1051
1052
1053         %% minDiff() FUNCTION
1054         function cost = minDiff(obj,x1,x2)
1055             % cost function minimized by reduced differences on the statistic
1056             cost = (abs((x2-x1))^obj.exp)*obj.weight;
1057         end % minDiff
1058
1059
1060         %% maxDiff() FUNCTION
1061         function cost = maxDiff(obj,x1,x2)
1062             % cost function minimized by maximizing differences on the stat.  Many uses may want to use orderedMaxDiff, instead.
1063             cost = (-(abs((x2-x1))^obj.exp))*obj.weight;
1064         end
1065
1066         %% orderedMaxDiff() FUNCTION
1067         function cost = orderedMaxDiff(obj,x1,x2)
1068             % cost function minimized by maximizing a difference between the two groups that adheres to s1.stat < s2.stat
1069             if x1 < x2; cost = (-(abs((x2-x1))^obj.exp))*obj.weight;
1070             else cost = ((abs((x2-x1))^obj.exp))*obj.weight; end;
1071         end
1072
1073         %% cost = acceptSwap(obj)
1074         function cost = acceptSwap(obj)
1075             %generic acceptSwap function
1076             obj.acceptsw();
1077             cost = acceptSwap@genericConstraint(obj);
1078         end
1079
1080         %% cost = rejectSwap(obj)
1081         function cost = rejectSwap(obj)
1082             %generic reject function
1083             obj.rejectsw();
1084             cost = rejectSwap@genericConstraint(obj);
1085         end
1086
1087         %% acceptSwapMeans() METHOD
1088         function acceptSwapMeans(obj)
1089             % updates variables when the proposed swap is accepted for
1090             % means
1091
1092             if(isnan(obj.swstat1) && isnan(obj.swstat2))
1093                 %do nothing, this method does not need to update
1094             elseif(isnan(obj.swstat1) == false && isnan(obj.swstat2) == false)
1095               obj.stat1=obj.swstat1;
1096               obj.stat2=obj.swstat2;
1097
1098               obj.swstat1 = NaN;
1099               obj.swstat2 = NaN;
1100             else
1101                 error('This should not have happened.  Maybe NaN in data?');
1102             end
1103         end
1104
1105         %% rejectSwapMeans() METHOD
1106         function rejectSwapMeans(obj)
1107             % updates variables when swap is rejected
1108               obj.swstat1 = NaN;
1109               obj.swstat2 = NaN;
1110         end
1111
1112          %% acceptSwapStdev() METHOD
1113         function acceptSwapStdev(obj)
1114             % updates variables when the proposed swap is accepted for
1115             % standard deviations
1116
1117             if(isnan(obj.swstat1) && isnan(obj.swstat2))
1118                 %do nothing, this method does not need to update
1119             elseif(isnan(obj.swstat1) == false && isnan(obj.swstat2) == false)
1120
1121 %               disp('clearing swap memory');
1122               obj.stat1=obj.swstat1;
1123               obj.stat2=obj.swstat2;
1124
1125
1126               obj.sumx1sq = obj.swpsumx1sq;
1127               obj.meanx1 = obj.swpmeanx1;
1128
1129               obj.sumx2sq = obj.swpsumx2sq;
1130               obj.meanx2 = obj.swpmeanx2;
1131
1132               obj.swpsumx1sq = NaN;
1133               obj.swpmeanx1 = NaN;
1134
1135               obj.swpsumx2sq = NaN;
1136               obj.swpmeanx2 = NaN;
1137
1138               obj.swstat1 = NaN;
1139               obj.swstat2 = NaN;
1140             else
1141                 error('This should not have happened');
1142             end
1143         end
1144
1145         %% rejectSwapStdev() METHOD
1146         function rejectSwapStdev(obj)
1147             % updates variables when the proposed swap is rejected
1148
1149               obj.swpsumx1sq = NaN;
1150               obj.swpmeanx1 = NaN;
1151
1152               obj.swpsumx2sq = NaN;
1153               obj.swpmeanx2 = NaN;
1154
1155               obj.swstat1 = NaN;
1156               obj.swstat2 = NaN;
1157         end
1158     end
1159
1160
1161
1162
1163     methods (Static)
1164         %% p = softDistanceConstraintInputParser2Sample() STATIC METHOD
1165         function p = softDistanceConstraintInputParser2Sample()
1166             % generates an input parser with parameter / value pairs and validators for the constructor args
1167             %
1168             % See constructor help/doc for more details
1169
1170             p = inputParser;
1171
1172             %NOTE: though these technically are 'optional' according to
1173             %MATLAB's definition of what an input parser does, the fact
1174             %that most of their default values will fail validation in all cases
1175             %makes them de facto required parameters.
1176
1177             p.addParamValue('sosObj','null',@(sosObj)strcmp(class(sosObj),'sos'));
1178             p.addParamValue('constraintType', 'null', ...
1179                 @(constraintType)any(strcmp({'soft'},constraintType)));
1180             p.addParamValue('fnc','null', ...
1181                  @(fnc)any(strcmp({'min' 'max','orderedMax'},fnc)));
1182             p.addParamValue('stat','null', ...
1183                  @(stat)any(strcmp({'mean' 'stdev'},stat)));
1184             p.addParamValue('sample1','null',@(sample1)strcmp(class(sample1),'sample'));
1185             p.addParamValue('sample2','null',@(sample2)strcmp(class(sample2),'sample'));
1186             p.addParamValue('s1ColName','',@(s1ColName)ischar(s1ColName));
1187             p.addParamValue('s2ColName','',@(s2ColName)ischar(s2ColName));
1188             p.addParamValue('paired','null',@(paired)islogical(paired));
1189             p.addParamValue('exponent',2,@(exponent)isnumeric(exponent));
1190             p.addParamValue('weight',1,@(weight)isnumeric(weight));
1191             p.addParamValue('name','noname',@(name)ischar(name));
1192
1193         end % softDistanceConstraintInputParser()
1194
1195
1196
1197         function p = softDistanceConstraintInputParser1Sample()
1198             % generates an input parser with parameter / value pairs and validators for the constructor args
1199             %
1200             % See constructor help/doc for more details
1201
1202             p = inputParser;
1203
1204             %NOTE: though these technically are 'optional' according to
1205             %MATLAB's definition of what an input parser does, the fact
1206             %that most of their default values will fail validation in all cases
1207             %makes them de facto required parameters.
1208
1209             p.addParamValue('sosObj','null',@(sosObj)strcmp(class(sosObj),'sos'));
1210             p.addParamValue('constraintType', 'null', ...
1211                 @(constraintType)any(strcmp({'soft'},constraintType)));
1212             p.addParamValue('fnc','null', ...
1213                  @(fnc)any(strcmp({'match1SampleVal'},fnc)));
1214             p.addParamValue('stat','null', ...
1215                  @(stat)any(strcmp({'mean' 'stdev'},stat)));
1216             p.addParamValue('sample1','null',@(sample1)strcmp(class(sample1),'sample'));
1217             p.addParamValue('s1ColName','',@(s1ColName)ischar(s1ColName));
1218             p.addParamValue('exponent',2,@(exponent)isnumeric(exponent));
1219             p.addParamValue('weight',1,@(weight)isnumeric(weight));
1220             p.addParamValue('targVal','null',@(targVal)isnumeric(targVal));
1221             p.addParamValue('name','noname',@(name)ischar(name));
1222
1223         end % softDistanceConstraintInputParser()
1224
1225     end
1226
1227
1228     methods (Static, Access = private)
1229
1230         %% p = parse2SampleContructorArgs(varargin) STATIC PRIVATE FUNCTION
1231         function p = parse2SampleConstructorArgs(varargin)
1232             % parses the constructor args
1233             %
1234             % See constructor help/doc for more info
1235
1236             varargin = varargin{1};
1237             p = softDistanceConstraint.softDistanceConstraintInputParser2Sample();
1238             p.parse(varargin{:});
1239         end
1240
1241         %% p = parse1SampleContructorArgs(varargin) STATIC PRIVATE FUNCTION
1242         function p = parse1SampleConstructorArgs(varargin)
1243             % parses the constructor args
1244             %
1245             % See constructor help/doc for more info
1246
1247             varargin = varargin{1};
1248             p = softDistanceConstraint.softDistanceConstraintInputParser1Sample();
1249             p.parse(varargin{:});
1250         end
1251     end
1252
1253 end % end class
1254