Description of sos
Home > src > sos.m
sos
PURPOSE
- SOS optimization object
SYNOPSIS
This is a script file.
DESCRIPTION
 - SOS optimization object
 copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
    This file is part of SOS
    SOS is free software: you can redistribute it and/or modify
    it for academic and non-commercial purposes
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.  For commercial or for-profit
    uses, please contact the authors (sos@cnbc.cmu.edu).
    SOS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
CROSS-REFERENCE INFORMATION
This function calls:
dataFrame - dataframe object
expAnneal - exponentially-decaying temperature annealing object
genericStatTest - parent class for statistical test objects
greedyAnneal - greedy annealing (i.e., T = 0) object
logisticpSwapFunction - swap function based on the logistic curve
randPopulationAndSampleCandidateSelection - random population and sample selection method for swaps
randPopulationCandidateSelection - random population selection method for selecting swaps
randSampleCandidateSelection - random sample method for selecting swaps
sample - sample object
seconds2human - human readable time output
sos - SOS optimization object
sosHistory - object for storing the detailed history of an optimization
sosPlots - object used to create detailed plots of SOS optimization
sos_gui - sos main GUI
verbosePrint - master print function that regulates cmd line output based on verbosity flags
This function is called by:
sos - SOS optimization object
SUBFUNCTIONS
function obj = sos(varargin)
function obj = addSample(obj, sample)
function present = containsSample(obj, sample)
function constraint = addConstraint(obj, varargin)
function present = containsConstraint(obj, constraint)
function obj = initFillSamples(obj)
function validItem = checkHardConstraintsFilling(obj,sample,sItemIndex,newItemDataFrame,newItemIndex)
function swCost = checkHardConstraintsSwapping(obj,sample,sItemIndex,newItemDataFrame,newItemIndex)
function swCost = checkSoftConstraintsSwapping(obj,targSample,targSampleIndex,feederdf, feederdfIndex)
function swCost = checkMetaConstraintsSwapping(obj,~,~,~,~)
function [colName,colMean,colStd,allData] = normalizeData(obj)
function cost = initCost(obj)
function cost = dispCost(obj)
function setAnnealSchedule(obj,varargin)
function setSampleCandidateSelectionMethod(obj,methodName)
function setFeederdfCandidateSelectionMethod(obj,methodName)
function setpSwapFunction(obj,swFunctionName)
function goodEnding = optimize(obj,varargin)
function doReport(obj,tStart,startIt)
function createPlots(obj,dispIt)
function updatePlots(obj)
function createHistory(obj)
function updateHistory(obj,curIt,cost,deltaCost,pFlip,temp)
function writeHistory(obj,outFile)
function setBufferedHistoryOutfile(obj,outFile)
function enableBufferedHistoryWrite(obj)
function disableBufferedHistoryWrite(obj)
function writeSamples(obj)
function writePopulations(obj)
function writeAll(obj)
function addttest(obj, varargin)
function addztest(obj, varargin)
function addkstest(obj, varargin)
function pass = doStatTests(obj,varargin)
function deltaCostPercentiles(obj)
function p = sosInputParser()
function p = parseConstructorArgs(varargin)
SOURCE CODE
% - SOS optimization object
%
% copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
%
%    This file is part of SOS
%
%    SOS is free software: you can redistribute it and/or modify
%    it for academic and non-commercial purposes
%    under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.  For commercial or for-profit
%    uses, please contact the authors (sos@cnbc.cmu.edu).
%
%    SOS is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%    You should have received a copy of the GNU General Public License
%    along with SOS (see COPYING.txt).
%    If not, see <http://www.gnu.org/licenses/>.
classdef sos < genericStatTest
    % Creates and supports optimization objects
    %
    % Inherits from handle so that by-reference passing can be used with
    % the object
    %
    % PROPERTIES
    %     samples % array of samples linked to SOS object
    %     hardConstraints % array of hard constraint objects
    %     softConstraints % array of soft constraint objects
    %     metaConstraints % array of meta constraint objects
    %     cost % current cost
    %     sCandObj % object used to identify the target item in a sample which may be swapped
    %     feederCandObj % object used to identify the item in a population/other sample to be swapped with the target sample item
    %     pSwapObj  % object which determines the probability of making a swap based on deltaCost
    %     annealObj % object used to anneal temperature in pSwap
    %     maxIt % maximum number of iterations that an optimization will run for
    %     allData % merge of all data from all samples/ pops linked to sosobj
    %     allDataColName % name of columns in allData
    %     allDataColMean % mean for each column in allData
    %     allDataColStd  % stdev for each column in all data
    %     reportInterval % number of iterations between progress reports
    %     curIt % current optimization iteration
    %     curFreezeIt % number of iterations cost has been frozen at a particular value
    %     stopFreezeIt % number of frozen iterations before algorithm stops
    %     sosstattests % array of handles to sos  stat tests requested by user
    %     statInterval % number of iterations between stat reports
    %     statTestReportStyle % style of report ('short' or 'full')
    %     deltaCost % delta cost from soft constraints from last attempted flip that met all hard constraints
    %     blockSize % number of iterations in a 'block' of trials for which average flip history /minDeltaCost stats are calculated
    %     nFlip % number of flips so far in the block
    %     deltaCostLog % log of deltaCost values for delta cost distribution analysis
    %     oldNumIt % number of iterations requested on the last optimization.  This is the default number for future optimizations.
    %     plotObj % sos object responsible for plotting
    %     histObj % object that contains detailed optimization history data
    %
    % METHODS:
    %   sos(varargin) -  Constructor
    %   addSample(sample) adds a sample to the SOS object so that its items can be optimized.
    %   present = containsSample(sample) evaluates whether the sos object already contains the specified sample
    %   constraint = addConstraint(varargin) % Adds a constraint to be optimized and returns it
    %   initFillSamples() % fills all samples to their specified capacity
    %   validItem = checkHardConstraintsFilling(sample,sItemIndex,newItemDataFrame,newItemIndex) returns a flag indicating if newIem can be added to sample during the initial filling of samples.
    %   swCost = checkHardConstraintsSwapping(sample,sItemIndex,newItemDataFrame,newItemIndex) returns the hard constraint cost of swapping item from newItemDataframe with item in sample.
    %   swCost = checkSoftConstraintsSwapping(targSample,targSampleIndex,feederdf, feederdfIndex)  % calculates the cost of a swap on the soft constraints
    %   swCost = checkMetaConstraintsSwapping(~,~,~,~)  % calcualtes the cost of a swap on the meta constraints
    %   [colName,colMean,colStd,allData] = normalizeData() % Normalizes the data in the samples and populations linked to the SOS object to provide some coarse balancing of initial cost values.
    %   cost = initCost()  %initializes and reports hard/soft/meta cost contraints
    %   setpSwapFunction(obj,swFunctionName) %sets the pSwap function for the sos obj.
    %   setSampleCandidateSelectionMethod(methodName) % sets the sample Candidate selection method
    %   setFeederdfCandidateSelectionMethod(methodName)  % sets the feeder candidate selection method
    %   setAnnealSchedule(varargin) % sets the anneal schedule for the SOS object
    %   goodEnding = optimize()  % Optimizes samples based on specified constraints
    %   doReport(tStart)  % displays a progress report from the last iteration in optimization
    %   writeSamples() % writes the data from the samples to text files specified in their 'outFile' property
    %   writePopulations() % writes the data from the populations to text files specified in their 'outFile' property
    %   writeAll() write all populations and samples associated with SOS object to disk
    %   addttest(obj, varargin) %adds a t-test to the list of analyses to run
    %   addztest(varargin) %adds a z-test to the list of analyses to run
    %   pass = doStatTests(varargin) % runs the stat tests and indicates if all passed the user hypotheses.
    %   present = containsConstraint(constraint) % determines whether <constraint> is a constraint associated with the current SOSobj
    %   cost = dispCost()  %reports hard/soft/meta cost contraints
    %   deltaCostPercentiles() % displays the breakdown of deltaCost values per decile
    %   createPlots(dispIt) % creates plots for several optimization parameters
    %   updatePlots(curIt,cost,deltaCost,pFlip,temp) %updates the contents of the plot
    %   createHistory() % creates plots for several optimization parameters
    %   updateHistory(curIt,cost,deltaCost,pFlip,temp) %updates the contents of the plot
    %   writeHistory(fileName) %writes all history saved to date to file 'fileName'
    %   setBufferedHistoryOutfile(outFile) % writes the history on-line, one update at a time, to outfile
    %   enableBufferedHistoryWrite() % enables writing of buffered history.
    %   disbleBufferedHistoryWrite() % disables writing of buffered history.
    %
    % METHODS (STATIC,Acess = private)
    %   p = parseConstructorArgs(varargin) - parses the sos constructor arguments
    %% PROPERTIES
    properties
        samples % array of samples linked to SOS object
        hardConstraints % array of hard constraint objects
        softConstraints % array of soft constraint objects
        metaConstraints % array of meta constraint objects
        cost % current cost
        sCandObj % object used to identify the target item in a sample which may be swapped
        feederCandObj % object used to identify the item in a population/other sample to be swapped with the target sample item
        pSwapObj  % object which determines the probability of making a swap based on deltaCost
        annealObj % object used to anneal temperature in pSwap
        maxIt % maximum number of iterations that an optimization will run for
        allData % merge of all data from all samples/ pops linked to sosobj
        allDataColName % name of columns in allData
        allDataColMean % mean for each column in allData
        allDataColStd  % stdev for each column in all data
        reportInterval % number of iterations between progress reports
        curIt % current optimization iteration
        curFreezeIt % number of iterations cost has been frozen at a particular value
        stopFreezeIt % number of frozen iterations before algorithm stops
        sosstattests % array of handles to sos  stat tests requested by user
        statInterval % number of iterations between stat reports
        statTestReportStyle % style of report ('short' or 'full')
        deltaCost % delta cost from soft constraints from last attempted flip that met all hard constraints
        blockSize % number of iterations in a 'block' of trials for which average flip history /minDeltaCost stats are calculated
        nFlip % number of flips so far in the block
        deltaCostLog % log of deltaCost values for delta cost distribution analysis
        oldNumIt % number of iterations requested on the last optimization.  This is the default number for future optimizations.
        plotObj % object responsible for plotting
        histObj % object that contains detailed optimization history data
        targSampleCandSelectMethod % name of sample replacement method
        feederdfCandSelectMethod % name of neighbor method
        queryStopOptimize % how often to probe the gui to see if the stop button was pressed
    end
    %% PROPERTIES (Constant)
    properties (Constant)
        maxIt_def = 10000; % default
        pSwapFunction_def = 'logistic'; % default
        targSampleCandSelectMethod_def = 'random'; % default
        feederdfCandSelectMethod_def = 'randomPopulationAndSample'; % default
        reportInterval_def = 1000; % default
        stopFreezeIt_def = 10000; % default
        statInterval_def = 10000; % default
        statTestReportStyle_def = 'short'; % default
        blockSize_def = 1000; % default
        queryStopOptimize_def = 100; % default
    end
    methods
        %% sos CONSTRUCTOR
        function obj = sos(varargin)
            % Constructor
            %
            % SYNOPSIS:
            % Creates an SOS object
            %
            %PARAMETERS:
            %Optional:
            %   'maxIt'/integer - maximum number of iterations to run the optimizer
            %   'pSwapFunction'/string - name of pSwapFunction to use.
            %   'targSampleCandSelectMethod'/string - name of target Sample Candidate selection method
            %   'feederdfCandSelectMethod'/string - name of feeder dataframe candidate selection method
            %   'reportInterval'/int - number of iterations between general cost reports
            %   'stopFreezeIt'/int - operationalized number of sequential iterations cost value must remain the same for state to be considered 'frozen'
            %   'statInterval'/int - number of iterations between stat reports
            %   'statTestReportStyle'/string - style of stat reports ('short' or 'full')
            %   'blockSize'/int - number of iterations in a block; used to determine length of deltaCostLog
            verbosePrint([char(10) 'Creating sos Object'], ...
                'sos_constructor_startObjCreation');
            p = sos.parseConstructorArgs(varargin);
            %potentially user-specified variables
            obj.maxIt = p.Results.maxIt;
            obj.oldNumIt = obj.maxIt;
            obj.reportInterval = p.Results.reportInterval;
            obj.stopFreezeIt = p.Results.stopFreezeIt;
            obj.statInterval = p.Results.statInterval;
            obj.statTestReportStyle = p.Results.statTestReportStyle;
            obj.blockSize = p.Results.blockSize;
            obj.queryStopOptimize = obj.queryStopOptimize_def;
            setpSwapFunction(obj,p.Results.pSwapFunction);
            setSampleCandidateSelectionMethod(obj,...
                p.Results.targSampleCandSelectMethod);
            setFeederdfCandidateSelectionMethod(obj,...
                p.Results.feederdfCandSelectMethod);
            obj.targSampleCandSelectMethod = p.Results.targSampleCandSelectMethod;
            obj.feederdfCandSelectMethod = p.Results.feederdfCandSelectMethod;
            obj.curIt = 0;
            obj.samples = [];
            obj.hardConstraints = [];
            obj.softConstraints = [];
            obj.metaConstraints = [];
            obj.sosstattests = [];
            obj.curFreezeIt = 0;
            obj.deltaCost = NaN;
            obj.nFlip = NaN;
            obj.deltaCostLog = nan(obj.blockSize,1);
            %set default anneal schedule to greedy
            obj.setAnnealSchedule();
            verbosePrint(['Creation of sos object complete' char(10)], ...
                'sos_constructor_endObjCreation');
        end
        %% addSample METHOD
        function obj = addSample(obj, sample)
            % adds a sample to the SOS object so that its items can be optimized.
            %
            % CALL:
            % <sosObj>.addSample(<sampleObj>)
            %
            % PARAMETERS:
            % sample - a sample object
            p = inputParser;
            p.addRequired('obj');
            p.addRequired('sample', ...
                 @(sample)strcmp(class(sample),'sample'));
            p.parse(obj,sample);
            if(isempty(sample.population)==1)
                verbosePrint('Warning: Sample has not been linked with a population', ...
                    'sos_addSample_NoPopForSampleWarn');
            end
            present = obj.containsSample(sample);
            if(present == 1)
                verbosePrint('Warning: Sample has already been added.  It cannot be added again', ...
                    'sos_addSample_SampleAlreadyAddedWarn');
            else
                obj.samples = [obj.samples sample];
                verbosePrint('Adding new Sample...', ...
                    'sos_addSample_sampleAdded');
            end
        end %addSample
        %% present = containsSample(sample) METHOD
        function present = containsSample(obj, sample)
            % evaluates whether the sos object already contains the specified sample
            %
            % PARAMETERS:
            %   sample - a sample object
            p = inputParser;
            p.addRequired('obj');
            p.addRequired('sample', ...
                 @(sample)strcmp(class(sample),'sample'));
            p.parse(obj,sample);
            present = max(ismember(obj.samples,sample));
        end %addSample
        %% addConstraint(varargin) METHOD
        function constraint = addConstraint(obj, varargin)
           % Adds a constraint to be optimized
           %
           % PARAMETERS:
           % varies dependig on object to be created.  See
           % genericConstraint and the specific constraint you wish to
           % create for options.
           constraint = genericConstraint.createConstraint('sosObj',obj,varargin{:});
           if(strcmp(constraint.constraintType,'hard'))
               obj.hardConstraints = [obj.hardConstraints {constraint}];
           elseif(strcmp(constraint.constraintType,'soft'))
               obj.softConstraints = [obj.softConstraints {constraint}];
           elseif(strcmp(constraint.constraintType,'meta'))
               obj.metaConstraints = [obj.metaConstraints {constraint}];
           else
               error('The type of the new constraint is not supported by the sos object.  Supported types are hard/soft/meta');
           end
        end
        %% present = containsConstraint(constraint) METHOD
        function present = containsConstraint(obj, constraint)
            % determines whether <constraint> is a constraint associated with the current SOSobj
            %
            % Returns 1 if <constraint> is present, 0 otherwise
            present = 0;
            for i=1:length(obj.hardConstraints)
                if(obj.hardConstraints{i} == constraint)
                    present = 1;
                    return;
                end
            end
            for i=1:length(obj.softConstraints)
                if(obj.softConstraints{i} == constraint)
                    present = 1;
                    return;
                end
            end
            for i=1:length(obj.metaConstraints)
                if(obj.metaConstraints{i} == constraint)
                    present = 1;
                    return;
                end
            end
        end
        %% initFillSamples()  METHOD
        function obj = initFillSamples(obj)
            % fills all samples to their specified capacity
            %
            verbosePrint('Filling All Samples...','sos_initFillSamples_start');
            if(isempty(obj.samples))
                 error('Error: No Samples in SOS Object!');
            end
            %total add stores references to the number of items left to
            %fill in to all of the different samples.
            totalAdd = [];
            for i=1:length(obj.samples)
               %find out how many observations are needed,
               %how many have already been filled,
               %and then fill the remainder
               n = obj.samples(i).n;
               if(isempty(obj.samples(i).data))
                   curN= 0;
               else
                curN = length(obj.samples(i).data{1});
               end
               toAdd = n-curN;
               totalAdd = [totalAdd ones(1,toAdd)*i]; %#ok<AGROW>
            end
           %now add all of those observations from the appropriate
           %population, enforcing hard bounds
           while(isempty(totalAdd) ==0)
               %select a sample at random
               toAddIndex=floor((length(totalAdd)*rand)+1);
               sIndex= totalAdd(toAddIndex);
               %randomly select an item from it's population:
                %make sure that the target population has at least one
                %item still in it
                if(isempty(obj.samples(sIndex).population))
                    error(['Sample ''',obj.samples(sIndex).name,''' is not filled to capacity, but has not been linked to a population to fill it']);
                end
                if(isempty(obj.samples(sIndex).population.data)==1)
                    error(['sos.initFillSamples Failed because ', ...
                        'a population was depeleted of items but ',...
                        'more items were still needed']);
                else
                    pItemIndex = ...
                     floor(length(obj.samples(sIndex).population.data{1})*rand+1);
                end
                if(isempty(obj.samples(sIndex).data))
                    sItemIndex = 1;
                else
                    sItemIndex = length(obj.samples(sIndex).data{1});
                end
                %pass it the current sample, where the item will go in it,
                %then the population, and the item from the pop's index.
                validItem = obj.checkHardConstraintsFilling( ...
                    obj.samples(sIndex),sItemIndex, ...
                    obj.samples(sIndex).population,pItemIndex);
                if(validItem == 1)
                    %add that population item to the sample list; remove it
                    %from the population.
                    totalAdd(toAddIndex)=[]; %#ok<AGROW>
                    pItem = obj.samples(sIndex).population.popItem(pItemIndex);
                    obj.samples(sIndex).appendItem(pItem);
                end
           end
        end % initFillSamples
        %% validItem = checkHardConstraintsFilling(obj,sample,sItemIndex,newItemDataFrame,newItemIndex)
        function validItem = checkHardConstraintsFilling(obj,sample,sItemIndex,newItemDataFrame,newItemIndex)
            % returns a flag indicating if newItem can be added to sample during the initial filling of samples.
            %
            % Should only be invoked when initially filling the samples
            %
            %
            %   sample - the target sample
            %   sItemIndex - row index of item to swap
            %   newItemDataframe - dataframe (sample/pop) containin the item to fill with.
            %   newItemIndex - row index of item to swap.
            validItem = 1;
            for i=1:length(obj.hardConstraints)
                if(obj.hardConstraints{i}.s1 == sample)
                    if (obj.hardConstraints{i}.itemCostFilling(...
                            sample,sItemIndex, ...
                            newItemDataFrame,newItemIndex) == 1)
                        validItem = 0;
                    end
                end
            end
        end % checkHardConstraintsFilling
        %% swCost = checkHardConstraintsSwapping(obj,sample,sItemIndex,newItemDataFrame,newItemIndex)
        function swCost = checkHardConstraintsSwapping(obj,sample,sItemIndex,newItemDataFrame,newItemIndex)
            % returns the hard constraint cost of swapping item from newItemDataframe with item in sample.
            %
            % Generally, if swCost > 0 the swap should not be executed
            %   sample - the target sample
            %   sItemIndex - row index of item to swap
            %   newItemDataframe - dataframe (sample/pop) containin the item to fill with.
            %   newItemIndex - row index of item to swap.
            curCost = 0;
            newCost = 0;
            for i=1:length(obj.hardConstraints)
                if(obj.hardConstraints{i}.s1 == sample)
                    curCost = curCost + obj.hardConstraints{i}.cost;
                    newCost = newCost + obj.hardConstraints{i}.swapCost(...
                        sample,sItemIndex,newItemDataFrame,newItemIndex);
                elseif (obj.hardConstraints{i}.s1 == newItemDataFrame)
                    curCost = curCost + obj.hardConstraints{i}.cost;
                    newCost = newCost + obj.hardConstraints{i}.swapCost(...
                        newItemDataFrame,newItemIndex,sample,sItemIndex);
                end
            end
            swCost = newCost - curCost ;
        end
        %% swCost =  checkSoftConstraintsSwapping(targSample,targSampleIndex,feederdf, feederdfIndex)
        function swCost = checkSoftConstraintsSwapping(obj,targSample,targSampleIndex,feederdf, feederdfIndex)
            % calculates the cost of a swap on the soft constraints
            %
            % PARAMETERS:
            %   targSample - the target sample
            %   targSampleIndex - row index of item to swap
            %   feederdf - dataframe (sample/pop) containin the item to fill with.
            %   feederdfIndex - row index of item to swap.
            %
            % RETURNS:
            % swCost - cost of making the swap
            swCost = 0;
            for j=1:length(obj.softConstraints)
                if ((obj.softConstraints{j}.s1 == targSample ||  ...
                        obj.softConstraints{j}.s2 == targSample || ...
                        obj.softConstraints{j}.s1 == feederdf || ...
                        obj.softConstraints{j}.s2 == feederdf ))
                    swCost = swCost + ...
                      obj.softConstraints{j}.swapCost(...
                       targSample,targSampleIndex,feederdf, feederdfIndex);
                else
                    swCost = swCost +obj.softConstraints{j}.cost;
                end
            end
        end
        %% swCost = checkMetaConstraintsSwapping(~,~,~,~) METHOD
        function swCost = checkMetaConstraintsSwapping(obj,~,~,~,~)
            % calcualtes the cost of a swap on the meta constraints
            %
            %Parameters:
            % parameters are the same as for hard and soft constraints, but
            % are ignored.  They are accepted as arguments merely to
            % increase the consistency of the argument.
            %checking meta constraints is extremely computationally cheap,
            %so they are calculated every time.
           swCost = 0;
           for j=1:length(obj.metaConstraints)
               swCost = swCost + obj.metaConstraints{j}.swapCost();
           end
        end
        %% [colName,colMean,colStd,allData] = normalizeData() METHOD
        function [colName,colMean,colStd,allData] = normalizeData(obj)
            % Normalizes the data in the samples and populations linked to the SOS object to provide some coarse balancing of initial cost values.
            verbosePrint('Normalizing Population and Sample Data', ...
                        'sos_normalizeData_start');
            %empty data frame
            allData = dataFrame();
            alreadyMerged = {};
            %go through each of the samples, and their populations.
            for i=1:length(obj.samples)
                %first, check the population:
                popPresent = 0;
                if(isempty(alreadyMerged))
                    popPresent = 0;
                else
                    for j=1:length(alreadyMerged)
                        if(alreadyMerged{j} == obj.samples(i).population)
                            popPresent = 1;
                        end
                    end
                end
                %population has not already been added, so add it
                if(popPresent == 0)
                    %only add the population if the sample does in fact
                    %have a population
                    if isempty(obj.samples(i).population) ~= 1
                        allData = dataFrame.aContainsb(allData,obj.samples(i).population);
                        allData = dataFrame.aContainsbData(allData,obj.samples(i).population);
                        alreadyMerged = [alreadyMerged {obj.samples(i).population}]; %#ok<AGROW>
                    end
                end
                %now add the sample
                allData = dataFrame.aContainsb(allData,obj.samples(i));
                allData = dataFrame.aContainsbData(allData,obj.samples(i));
                %we don't need to check that the sample hasn't been added
                %stricly speaking, because samples can only appear once.
                %However, this may be necessary in a future version of
                %the code...
                alreadyMerged = [alreadyMerged {obj.samples(i)}]; %#ok<AGROW>
            end
            %we now have all of the data in a single dataframe; each column
            %can now be normalized and descriptive statistics stored.
            colName = cell(1,length(allData.data));
            colMean = NaN(1,length(allData.data));
            colStd =  NaN(1,length(allData.data));
            for i=1:length(allData.data)
                %if it's a numeric vector, calculate mean/stdev
                colName{i} = allData.header{i};
                if(strcmp(allData.format{i},'%f'))
                   colMean(i) = nanmean(allData.data{i});
                   colStd(i) = nanstd(allData.data{i});
                end
            end
            %configure the z-data field in each sample and population to
            %reflect the new changes.
            for i=1:length(alreadyMerged)
               %link the current normalization to this object
                alreadyMerged{i}.sosObj = obj; %#ok<AGROW>
                alreadyMerged{i}.zdata = {}; %#ok<AGROW>
               for j=1:length(alreadyMerged{i}.data)
                   col = alreadyMerged{i}.data{j};
                  if(strcmp(alreadyMerged{i}.format{j},'%f'))
                      m= NaN;
                      std = NaN;
                      %get the relevant coefficients:
                      for k=1:length(colName)
                         if (strcmp(colName{k},alreadyMerged{i}.header{j}))
                            m = colMean(k);
                            std = colStd(k);
                             break;
                         end
                      end
                      %check that m and std exist
                      if(isnan(m) || isnan(std))
                          error('Normalization failed because either the mean or stdeviation was NaN');
                      end
                      %they exist, so normalization can proceed
                      if std == 0
                          verbosePrint(['Warning: No variance in column: ', alreadyMerged{i}.header{j}],...
                            'sos_normalizeData_noVarWarn');
                          std = 1;
                      end
                      col = (col-m)/std;
                  end
                  alreadyMerged{i}.zdata{j} = col; %#ok<AGROW>
               end
            end
            obj.allData = allData;
            obj.allDataColName = colName;
            obj.allDataColMean = colMean;
            obj.allDataColStd = colStd;
        end %normalizeData
        %% initCost() METHOD
        function cost = initCost(obj)
            %initializes and reports hard/soft/meta cost contraints
            verbosePrint([char(10),'Initializing Constraints',char(10)],...
                'sos_initCost_startInit');
            % hard constraints
            hardConstraintCost = 0;
            for j = 1:length(obj.hardConstraints)
                try
                    tempCost = obj.hardConstraints{j}.initCost();
                catch exception
                    if strcmp(exception.identifier, ...
                            'MATLAB:cellRefFromNonCell')
                        error(['ERROR: Data needed to calculate hard constraint cost #' num2str(j),' is missing.',...
                            char(10),'       Have samples been filled and normalized?']);
                    else
                        throw exception
                    end
                end
                verbosePrint(['   Hard Constraint #: ',num2str(j),...
                    ' Cost: ' num2str(tempCost),'   ',obj.hardConstraints{j}.name], ...
                        'sos_initCost_indivHardCost');
                hardConstraintCost = hardConstraintCost + tempCost;
            end
            verbosePrint(['Hard Constraint Total: ', num2str(hardConstraintCost)], ...
                        'sos_initCost_totalHardCost');
            % soft constraints
            softConstraintCost = 0;
            for j=1:length(obj.softConstraints)
                try
                    tempCost = obj.softConstraints{j}.initCost();
                catch exception
                    if strcmp(exception.identifier, ...
                            'MATLAB:cellRefFromNonCell')
                        error(['ERROR: Data needed to calculate soft constraint cost #' num2str(j),' is missing.',...
                            char(10),'       Have samples been filled and normalized?']);
                    else
                        throw exception
                    end
                end
                verbosePrint(['   Soft Constraint #: ',num2str(j),...
                    ' Cost: ' num2str(tempCost),'   ',obj.softConstraints{j}.name], ...
                        'sos_initCost_indivSoftCost');
               softConstraintCost = softConstraintCost + tempCost;
            end
            verbosePrint(['Soft Constraint Total: ', num2str(softConstraintCost)], ...
                        'sos_initCost_totalSoftCost');
            % meta constraints
            metaConstraintCost = 0;
            for j=1:length(obj.metaConstraints)
                try
                    tempCost = obj.metaConstraints{j}.initCost();
                catch exception
                    if strcmp(exception.identifier, ...
                            'MATLAB:cellRefFromNonCell')
                        error(['ERROR: Data needed to calculate meta constraint cost #' num2str(j),' is missing.',...
                            char(10),'       Have samples been filled and normalized?']);
                    else
                        throw exception
                    end
                end
                verbosePrint(['   Meta Constraint #: ',num2str(j),...
                    ' Cost: ' num2str(tempCost),'   ',obj.metaConstraints{j}.name], ...
                        'sos_initCost_indivMetaCost');
               metaConstraintCost = metaConstraintCost + tempCost;
            end
            verbosePrint(['Meta Constraint Total: ', num2str(metaConstraintCost)], ...
                        'sos_initCost_totalMetaCost');
            cost = softConstraintCost + metaConstraintCost;
            obj.cost=cost;
            verbosePrint([char(10),'TOTAL COST (soft + meta): ', num2str(cost), char(10)], ...
                'sos_initCost_totalSoftMetaCost');
        end
        %% dispCost() METHOD
        function cost = dispCost(obj)
            %reports hard/soft/meta cost contraints
            verbosePrint([char(10),'Displaying Constraint Costs',char(10)],...
                'sos_dispCost_start');
            % hard constraints
            hardConstraintCost = 0;
            for j = 1:length(obj.hardConstraints)
                tempCost = obj.hardConstraints{j}.cost;
                verbosePrint(['   Hard Constraint #: ',num2str(j),...
                    ' Cost: ' num2str(tempCost),'   ',obj.hardConstraints{j}.name], ...
                        'sos_dispCost_indivHardCost');
                hardConstraintCost = hardConstraintCost + tempCost;
            end
            verbosePrint(['Hard Constraint Total: ', num2str(hardConstraintCost)], ...
                        'sos_dispCost_totalHardCost');
            % soft constraints
            softConstraintCost = 0;
            for j=1:length(obj.softConstraints)
                tempCost = obj.softConstraints{j}.cost;
                verbosePrint(['   Soft Constraint #: ',num2str(j),...
                    ' Cost: ' num2str(tempCost),'   ',obj.softConstraints{j}.name], ...
                        'sos_dispCost_indivSoftCost');
               softConstraintCost = softConstraintCost + tempCost;
            end
            verbosePrint(['Soft Constraint Total: ', num2str(softConstraintCost)], ...
                        'sos_dispCost_totalSoftCost');
            % meta constraints
            metaConstraintCost = 0;
            for j=1:length(obj.metaConstraints)
                tempCost = obj.metaConstraints{j}.cost;
                verbosePrint(['   Meta Constraint #: ',num2str(j),...
                    ' Cost: ' num2str(tempCost),'   ',obj.metaConstraints{j}.name], ...
                        'sos_dispCost_indivMetaCost');
               metaConstraintCost = metaConstraintCost + tempCost;
            end
            verbosePrint(['Meta Constraint Total: ', num2str(metaConstraintCost)], ...
                        'sos_dispCost_totalMetaCost');
            cost = softConstraintCost + metaConstraintCost;
            %obj.cost=cost;
            verbosePrint([char(10),'TOTAL COST (soft + meta): ', num2str(cost), char(10)], ...
                'sos_dispCost_totalSoftMetaCost');
            if isnan(cost)
                verbosePrint([char(10), ...
                    'Warning: Cost was NaN.  This should not happen if cost terms ',...
                    char(10),'         are present and cost has been initialized',...
                    char(10)], 'sos_dispCost_warnCostNaN');
            end
        end %dispCost
        %% setAnnealSchedule(varargin) METHOD
        function setAnnealSchedule(obj,varargin)
            % sets the anneal schedule for the SOS object
            %
            % PARAMETERS:
            % Required:
            % 'schedule'/scheduleName - param/value pair indicating the name of the anneal schedule to use.  Defaults to greedy'
            %
            % Optional:
            %  - As required by specific schedule to create.  See its
            %  constructor for details.
            p = inputParser;
            p.addRequired('obj', @(obj)strcmp(class(obj),'sos'));
            p.addParamValue('schedule','greedy', ...
                @(schedule)ischar(schedule));
            p.KeepUnmatched = true;
            % in case no parameters are passed to varargin, must make the
            % following decision
            if(isempty(varargin) == false)
                 p.parse(obj,varargin{:});
            else
                p.parse(obj);
            end
            scheduleName = p.Results.schedule;
            if any(strcmp(p.UsingDefaults,'schedule'))
                verbosePrint(['    Defaulting to ', scheduleName, ' annealing...'], ...
                    'sos_setAnnealSchedule_defaultAnneal');
            end
           if(strcmp(scheduleName, 'greedy') == 1)
               obj.annealObj = greedyAnneal(varargin{:});
           elseif (strcmp(scheduleName, 'exp') == 1)
                obj.annealObj = expAnneal(varargin{:});
           else
               error(['There is no schedule named: ' schedule])
           end
        end
        %% setSampleCandidateSelectionMethod(methodName) METHOD
        function setSampleCandidateSelectionMethod(obj,methodName)
            % sets the sample Candidate selection method
            %
            %PARAMETERS:
            % Name of a sampleCandidateSelectionMethod
            if (ischar(methodName) == false)
                error('{methodName} must be a string');
            end
           if (strcmp(methodName, 'random') == 1)
                obj.sCandObj = randSampleCandidateSelection(obj);
           else
               error(['Specified methodName ',methodName,' does not exist']);
           end
        end
        %% setFeederdfCandidateSelectionMethod(obj,methodName)
        function setFeederdfCandidateSelectionMethod(obj,methodName)
            % sets the feeder candidate selection method
            %
            %PARAMETERS:
            % name of a feederCandidateSelectionMethod
            if (ischar(methodName) == false)
                error('{methodName} must be a string');
            end
           if (strcmp(methodName, 'randomPopulation') == 1)
                obj.feederCandObj= randPopulationCandidateSelection();
                obj.feederdfCandSelectMethod = methodName;
           elseif (strcmp(methodName, 'randomPopulationAndSample') == 1)
                obj.feederCandObj= randPopulationAndSampleCandidateSelection(obj);
                obj.feederdfCandSelectMethod = methodName;
           else
                error('Specified {methodName} does not exist');
           end
        end
         %% setpSwapFunction(methodName) METHOD
         function setpSwapFunction(obj,swFunctionName)
             %sets the pSwap function for the sos obj.
             %
             %PARAMETERS:
             %  swFunctionName - name of swap function.  Currently, 'logicistic' is the only supported function.
            if (ischar(swFunctionName) == false)
                error('SOS:setSwapFunction {swFunctionName} is not a valid string');
            end
           if (strcmp(swFunctionName, 'logistic'))
                obj.pSwapObj = logisticpSwapFunction();
           else
                error('SOS:setpSwapFunction: specified function does not exist');
           end
        end %setpSwapFunction
        %% optimize() METHOD
        function goodEnding = optimize(obj,varargin)
            % Optimizes samples based on specified constraints
            %
            % PARAMETERS
            %   numIt - number of iterations to run (otherwises uses
            %           default from obj init)
            %   'isGui' / 1 or 0 - flag denoting whether there is an active gui or not
            % RETURNS:
            %   1 if ended because statistical constraints reached, zero
            %   otherwise
            % It would be possible to seperate the normalization and
            % costInitialization procedures so that they need not be run
            % every time you begin optimizing.  In fact, the current code
            % probably enforces such a constraint and should generate an
            % error if normalization is attempted anyways.  Nevertheless,
            % it costs little to enforce it at this point in time given
            % that most time should be spent trying to make swaps, so it's
            % left that way in this version of the code.  In the future, it
            % may be useful to avoid any possible redundancy here, and also
            % consider adding the fillSamples() command to the
            % pre-optimization procedure.
            verbosePrint(['Setting up optimization procedure...', ...
                        char(10)], 'sos_optimize_begin');
            %get all parameters passed to the alogirthm
            p = inputParser;
            p.addOptional('numIt',-1);
            p.addParamValue('isGui',NaN);
            p.parse(varargin{:});
            if any(strcmp(p.UsingDefaults,'numIt'))
                % do nothing, allow defaults to be used
            else
                numIt = p.Results.numIt;
                validateattributes(numIt, {'numeric'}, ...
                    {'scalar', 'integer', 'positive', '>', 0})
                obj.maxIt = obj.curIt + numIt;
                obj.oldNumIt = numIt;
            end
            if any(strcmp(p.UsingDefaults,'isGui'))
                % do nothing, no gui
                isGui = 0;
            else
                isGui = p.Results.isGui;
                if isGui == 1
                    mainWindowHandle = sos_gui; %this connects/ launches the gui
                    mainWindowData = guidata(mainWindowHandle);
                    set(mainWindowData.pushbutton_stopOptimize,'UserData',0)
                elseif isGui == 0
                    % do nothing
                else
                    error('isGui should be a flag with value 1 or 0).');
                end
            end
            % flag indicating whether the optimization should be
            % stopped or not, as inidicated in the GUI
            stopOptimize = 0;
            goodEnding = 0;
            % make sure that there are samples linked with the object
            % before running.
            if isempty(obj.samples)
                error('Cannot start optimization - there are no samples to optimize');
            end
           if isempty(obj.pSwapObj)
                error('Cannot start optimization - the annealing schedule must be set (e.g., greedy, exp)');
            end
            % next, make sure that all of the samples have been filled.
            for i=1:length(obj.samples)
                if isempty(obj.samples(i).data)
                    error(['Cannot start optimization - sample ''',...
                        obj.samples(i).name,''' is empty']);
                elseif length(obj.samples(i).data{1}) < obj.samples(i).n
                    error(['Cannot start optimization - sample ''',...
                        obj.samples(i).name,''' is missing items.  Did you initFillSamples()?']);
                end
            end
            if(obj.curIt == obj.maxIt)
                obj.maxIt = obj.maxIt+obj.oldNumIt;
            elseif obj.curIt > obj.maxIt
                error('Cannot start Optimization - curIt should never be greater than maxIt.  Increase by <SOSobj>.maxIt = <larger val>?');
            end
            if(obj.curFreezeIt == obj.stopFreezeIt)
                obj.curFreezeIt = 0;
                verbosePrint('curFreezeIt was at maximum value at start of optimization; resetting to 0', ...
                'sos_optimize_resetFreezeIt');
            end
1000
1001             obj.normalizeData();
1002             obj.initCost();
1003
1004             % set up the sample and neighbor replacement methods
1005             obj.setSampleCandidateSelectionMethod(obj.targSampleCandSelectMethod);
1006             obj.setFeederdfCandidateSelectionMethod(obj.feederdfCandSelectMethod);
1007
1008
1009
1010             verbosePrint(['Optimizing for ', num2str(obj.maxIt-obj.curIt), ' iterations'], ...
1011                 'sos_optimize_startOptimization');
1012
1013             tStart = tic;
1014             startIt = obj.curIt;
1015             allStatsPass = NaN;
1016
1017             reportHeader = [char(10), ' Iteration              Cost  %Complete       Elapsed   Remaining'];
1018             verbosePrint(reportHeader,'sos_optimize_reportHeader');
1019
1020             while obj.curIt<obj.maxIt && ...
1021                     obj.curFreezeIt < obj.stopFreezeIt && ...
1022                     allStatsPass ~= 1 && ...
1023                     stopOptimize == 0
1024                 obj.curIt=obj.curIt+1;
1025
1026                 if mod(obj.curIt,obj.reportInterval) == 0  || obj.curIt == 1
1027                     obj.doReport(tStart,startIt);
1028                      obj.doStatTests('reportStyle','none');
1029
1030                     if isempty(obj.histObj) == 0
1031                         %updatePlots
1032                         pFlip = obj.nFlip/obj.reportInterval;
1033                         obj.updateHistory(obj.curIt,obj.cost,...
1034                               obj.deltaCost,pFlip,obj.annealObj.getTemp());
1035                         obj.nFlip = 0;
1036
1037                         if isempty(obj.plotObj) == 0
1038                             obj.updatePlots();
1039                         end
1040                     end
1041                 end
1042
1043
1044                 %select items to swap
1045                 [targSample,targSampleIndex] = obj.sCandObj.getCandidateIndex();
1046                 [feederdf, feederdfIndex] = obj.feederCandObj.getCandidateIndex(targSample);
1047
1048
1049                 % check to see how swap fares with regard to hard
1050                 % constraints.  Abort swap if it would lead to an
1051                 % (increased) violation of hard constraints.
1052                 sumHardswCost = obj.checkHardConstraintsSwapping(...
1053                        targSample,targSampleIndex,feederdf, feederdfIndex);
1054
1055                 %if hard constraint was not violated or improved continue.
1056                 %A value < 0 indicates that hard constraint was improved so
1057                 %there will be a swap no matter what the soft cost.
1058                 if sumHardswCost <= 0
1059                    curCost = obj.cost;
1060
1061                     sumSoftswCost = obj.checkSoftConstraintsSwapping(...
1062                        targSample,targSampleIndex,feederdf, feederdfIndex);
1063
1064                     sumMetaswCost = obj.checkMetaConstraintsSwapping(...
1065                        targSample,targSampleIndex,feederdf, feederdfIndex);
1066
1067                     swCost = sumSoftswCost + sumMetaswCost;
1068                     %sign flipped so that if swCost < curCost, we get a
1069                     %negative value, and negative values descend in cost
1070                     %space
1071
1072                     deltaCost = -1*(curCost - swCost); %#ok<PROP>
1073
1074                     % if a swap is possible based on hard constraints, but
1075                     % not necessary, base decision to swap on soft
1076                     % constraints
1077                     if sumHardswCost == 0
1078                         shouldSwap = obj.pSwapObj.shouldSwap(...
1079                             deltaCost,obj.annealObj.getTemp()); %#ok<PROP>
1080
1081                         obj.deltaCost = deltaCost; %#ok<PROP>
1082
1083
1084
1085                     else %swap is necessary based on hard constraints.
1086                         shouldSwap = 1;
1087
1088                     end
1089
1090                     if shouldSwap == 1
1091
1092                         obj.nFlip = obj.nFlip + 1;
1093
1094
1095                         %we need to swap items
1096                         targSample.swapItems(...
1097                         targSampleIndex,feederdf, feederdfIndex,obj);
1098
1099                         %update constraints
1100                         for j = 1:length(obj.hardConstraints)
1101                             obj.hardConstraints{j}.acceptSwap();
1102                         end
1103
1104                         for j=1:length(obj.softConstraints)
1105                             obj.softConstraints{j}.acceptSwap();
1106                         end
1107
1108                         for j=1:length(obj.metaConstraints)
1109                             obj.metaConstraints{j}.acceptSwap();
1110                         end
1111
1112                         % see if the set is frozen
1113                         if sumHardswCost < 0
1114                             obj.curFreezeIt = 0;
1115                         elseif obj.cost ~= swCost
1116                             obj.curFreezeIt = 0;
1117                         else % we're swapping items with the same cost
1118                             obj.curFreezeIt = obj.curFreezeIt +1;
1119                         end
1120
1121                         obj.cost = swCost;
1122                     else
1123                         % reject the swap:
1124                         for j = 1:length(obj.hardConstraints)
1125                             obj.hardConstraints{j}.rejectSwap();
1126                         end
1127
1128                         for j=1:length(obj.softConstraints)
1129                             obj.softConstraints{j}.rejectSwap();
1130                         end
1131
1132                         for j=1:length(obj.metaConstraints)
1133                             obj.metaConstraints{j}.rejectSwap();
1134                         end
1135
1136                         obj.curFreezeIt = obj.curFreezeIt + 1;
1137
1138                     end
1139                 else
1140                     for j = 1:length(obj.hardConstraints)
1141                             obj.hardConstraints{j}.rejectSwap();
1142                     end
1143
1144                     obj.curFreezeIt = obj.curFreezeIt + 1;
1145                 end
1146                 %on some subset of the intervals, display relevant
1147                 %statistics.
1148
1149                 %mod indexing needed to have deltaCostLog loop after
1150                 %blockSize updates.
1151                 obj.deltaCostLog(mod(obj.curIt-1,obj.blockSize)+1) = obj.deltaCost;
1152
1153
1154                 obj.annealObj.anneal(obj.curIt,obj.cost,obj.deltaCost);
1155
1156                 % see if stats constraint has been met
1157                 if mod(obj.curIt,obj.statInterval) == 0
1158                     allStatsPass = ...
1159                         obj.doStatTests('reportStyle',obj.statTestReportStyle);
1160                     verbosePrint(reportHeader,'sos_optimize_reportHeader');
1161                 end
1162
1163                 %see if GUI interrupt has been requested
1164                 if isGui
1165                     % check to see if the stop button has been pressed
1166                     % every so often.  This should not be done too
1167                     % frequently as the drawnow event could take some time.
1168                     if mod(obj.curIt,obj.queryStopOptimize) == 0
1169                         drawnow;
1170                         if  get(mainWindowData.pushbutton_stopOptimize,'UserData') ~= 0
1171                             stopOptimize = 1;
1172                         end
1173                     end
1174                 end
1175
1176
1177             end %end iterations
1178
1179             %avoid a redundant report
1180             if mod(obj.curIt,obj.reportInterval) ~= 0 && obj.curIt ~= 1
1181                 obj.doReport(tStart,startIt);
1182                 obj.doStatTests('reportStyle','none');
1183
1184                 if isempty(obj.histObj) == 0
1185                     %updatePlots
1186                     pFlip = obj.nFlip/obj.reportInterval;
1187                     obj.updateHistory(obj.curIt,obj.cost,...
1188                           obj.deltaCost,pFlip,obj.annealObj.getTemp());
1189                     obj.nFlip = 0;
1190
1191                     if isempty(obj.plotObj) == 0
1192                         obj.updatePlots();
1193                     end
1194                 end
1195             end
1196
1197             if mod(obj.curIt,obj.statInterval) ~= 0
1198                     allStatsPass = ...
1199                         obj.doStatTests('reportStyle',obj.statTestReportStyle);
1200             end
1201
1202             % state the reason why optimization was stopped
1203            if (allStatsPass == 1)
1204                 verbosePrint([[char(10), 'Optimization ended after all statistical tests passed defined criteria', char(10)], ...
1205                         char(10)], 'sos_optimize_endallStatsPass');
1206                 goodEnding = 1;
1207            elseif obj.curIt == obj.maxIt
1208                 verbosePrint([char(10), 'Optimization ended after reaching the maximum number of iterations', ...
1209                         char(10)], 'sos_optimize_endMaxIt');
1210            elseif obj.curFreezeIt >= obj.stopFreezeIt
1211                 verbosePrint([char(10), 'Optimization ended after cost value was frozen for specified number of iterations', ...
1212                         char(10)], 'sos_optimize_endstopFreezeIt');
1213            elseif isGui
1214                if get(mainWindowData.pushbutton_stopOptimize,'UserData') == 1
1215                verbosePrint([char(10),'Optimization ended after user interrupt (from graphical interface)',...
1216                         char(10)],'sos_optimize_endUserGuiInterrupt');
1217                end
1218            end
1219
1220             if isGui == 1
1221                 mainWindowHandle = sos_gui; %this connects/ launches the gui
1222                 mainWindowData = guidata(mainWindowHandle);
1223                 set(mainWindowData.pushbutton_optimize,'Enable','on')
1224                 set(mainWindowData.pushbutton_stopOptimize,'Enable','off')
1225             end
1226
1227         end
1228
1229
1230         %% doReport (obj,tstart) METHOD
1231         function doReport(obj,tStart,startIt)
1232             % displays a progress report from the last iteration in optimization
1233             %
1234             %PARAMETERS:
1235             %   tStart - tic() object indicating start of optimization
1236
1237             percentComplete = (obj.curIt/obj.maxIt)*100;
1238             elapsedTime = toc(tStart);
1239
1240             startPercent = (startIt/obj.maxIt)*100;
1241
1242             remainingTime = (elapsedTime/ ...
1243                (percentComplete-startPercent))*(100-startPercent)-elapsedTime;
1244
1245             hElapsedTime = seconds2human(elapsedTime,'full');
1246             tempLen = length(hElapsedTime);
1247             hElapsedTime = strjust([blanks(8-tempLen) hElapsedTime],'right');
1248
1249             hRemainingTime = seconds2human(remainingTime,'full');
1250             tempLen = length(hRemainingTime);
1251             hRemainingTime = strjust([blanks(8-tempLen) hRemainingTime],'right');
1252
1253
1254             report = sprintf('%9.0f) \t %15.5f \t %5.2f%% \t %s \t %s', ...
1255                     obj.curIt,obj.cost,percentComplete, ...
1256                     hElapsedTime,hRemainingTime);
1257             verbosePrint(report, 'sos_optimize_report');
1258
1259         end
1260
1261         %% createPlots() METHOD
1262         function createPlots(obj,dispIt)
1263             % creates plots for several optimization parameters, as
1264             % follows:
1265             %   - cost
1266             %   - deltaCost
1267             %   - sosStatTestpvals
1268             %   - temperature
1269             %   - pFlipHistory
1270             %
1271             % PARAMETERS:
1272             %   dispIt - number of iterations to show on the plot screen.
1273             %       All other datapoints plotted since the creation of the
1274             %       object will still be accessible by scrolling the x-axis
1275
1276
1277             if isempty(obj.histObj)
1278                 obj.createHistory();
1279             end
1280
1281             if exist('dispIt','var') == 0
1282                 dispIt = 100000;
1283             else
1284                 validateattributes(dispIt, {'numeric'}, ...
1285                 {'scalar', 'integer', 'positive', '>', 0});
1286             end
1287
1288
1289             if isempty(obj.plotObj)
1290                 obj.plotObj = sosPlots(obj,obj.histObj,dispIt, ...
1291                                         obj.curIt);
1292             else
1293                 verbosePrint('Warning: Plots already exist so cannot be created',...
1294                     'sos_createPlots_alreadyCreated');
1295             end
1296         end
1297
1298         %% updatePlots() METHOD
1299         function updatePlots(obj)
1300             %updates the contents of the plot
1301
1302             obj.plotObj.updatePlots();
1303
1304         end
1305
1306
1307         %% createHistory() METHOD
1308         function createHistory(obj)
1309             % creates plots for several optimization parameters, as
1310             % follows:
1311             %   - cost
1312             %   - deltaCost
1313             %   - sosStatTestpvals
1314             %   - temperature
1315             %   - pFlipHistory
1316
1317             if isempty(obj.histObj)
1318
1319                 obj.histObj = sosHistory(obj);
1320             else
1321                 verbosePrint('Warning: History already exists so cannot be created',...
1322                     'sos_createHistory_alreadyCreated');
1323             end
1324
1325         end
1326
1327
1328         %% updateHistory() METHOD
1329         function updateHistory(obj,curIt,cost,deltaCost,pFlip,temp)
1330             %updates the contents of the plot
1331
1332             % get the information about the p-vals.
1333             testNames = {};
1334             testps = [];
1335
1336             for i=1:length(obj.sosstattests)
1337                 testNames = horzcat(testNames,obj.sosstattests{i}.label); %#ok<AGROW>
1338                 testps = horzcat(testps,obj.sosstattests{i}.lastp); %#ok<AGROW>
1339             end
1340
1341             obj.histObj.updateHistory(curIt,cost,deltaCost,pFlip, ...
1342                             testNames,testps,temp);
1343
1344         end
1345
1346         %% function writeHistory(outFile) METHOD
1347         function writeHistory(obj,outFile)
1348             %writes all history saved to date to file 'outFile'
1349
1350              if exist('outFile','var') == 0
1351                  error('"Outfile" argument was not supplied to writeHistory()');
1352              end
1353
1354              if(ischar(outFile) == false)
1355                 error('Outfile has not been set to a string != "null".');
1356              end
1357
1358             if isempty(obj.histObj) == 0
1359                 obj.histObj.writeHistory(outFile);
1360             else
1361                 error('No saved history to write - did you run createHistory() before optimizing?');
1362             end
1363         end
1364
1365         %% setbufferedHistoryOutfile(outFile) METHOD
1366         function setBufferedHistoryOutfile(obj,outFile)
1367             % writes the history on-line, one update at a time, to outfile
1368             % If outfile exists, it will be overridden.
1369
1370             if exist('outFile','var') == 0
1371                 error('"Outfile" argument was not supplied to writeHistory()');
1372             end
1373
1374             if(ischar(outFile) == false)
1375                 error('Outfile has not been set to a string != "null".');
1376             end
1377
1378             if ischar(outFile) == false || strcmp(outFile,'null')
1379                 error('Outfile has not been set to a string != "null".');
1380             end
1381
1382             if isempty(obj.histObj) == 0
1383                 obj.histObj.setBufferedHistoryOutfile(outFile);
1384             else
1385                 error('No saved history to write - did you start recording history with createHistory()?');
1386             end
1387         end
1388
1389         %% enableBufferedHistoryWrite() METHOD
1390         function enableBufferedHistoryWrite(obj)
1391             % enables writing of buffered history.  Enabled automatically
1392             % when bufferedHistoryWrite is first called; cannot be called
1393             % until that method has first been called to specify an
1394             % outfile.  Subsequent enablings continue to write to that
1395             % file.
1396
1397             if isempty(obj.histObj) == 0
1398                 obj.histObj.enableBufferedHistoryWrite();
1399             else
1400                 error('History is not being recorded so buffered writing cannot be enabled - run createHistory() first');
1401             end
1402         end
1403
1404         %% disableBufferedHistoryWrite() METHOD
1405         function disableBufferedHistoryWrite(obj)
1406             % disables writing of buffered history.
1407
1408             if isempty(obj.histObj) == 0
1409                 obj.histObj.disableBufferedHistoryWrite();
1410             else
1411                 error('History is not being recorded so buffered writing cannot be disabled - run createHistory() first');
1412             end
1413         end
1414
1415
1416         %% writeSamples()  METHOD
1417         function writeSamples(obj)
1418            % writes the data from the samples to text files specified in their 'outFile' property
1419
1420            verbosePrint('Writing all samples to disk...',...
1421                             'sos_writeSamples_begin');
1422
1423            for i=1:length(obj.samples)
1424                obj.samples(i).writeData();
1425            end
1426         end %writeSamples()
1427
1428         %% writePopulations()  METHOD
1429         function writePopulations(obj)
1430            % writes the data from the populations to text files specified in their 'outFile' property
1431
1432            verbosePrint('Writing all populations to disk...',...
1433                             'sos_writePopulations_begin');
1434
1435            alreadyWritten = {};
1436            popWritten = 0;
1437
1438            for i=1:length(obj.samples)
1439                if isempty(alreadyWritten)
1440                    popWritten = 0;
1441                else
1442                 for j = 1:length(alreadyWritten)
1443                     if (alreadyWritten{j} == obj.samples(i).population)
1444                         popWritten = 1;
1445                     end
1446                 end
1447                end
1448
1449                if(popWritten == 0)
1450                 obj.samples(i).population.writeData();
1451                 alreadyWritten = [alreadyWritten {obj.samples(i).population}]; %#ok<AGROW>
1452                end
1453            end
1454         end %writeSamples()
1455
1456         %% writeAll() METHOD
1457         function writeAll(obj)
1458             %write all populations and samples associated with SOS object to disk
1459             obj.writeSamples();
1460             obj.writePopulations();
1461
1462         end % writeAll()
1463
1464         %% addttest(sample1, sample2, s1ColName, s2ColName, type) METHOD
1465         function addttest(obj, varargin)
1466                 %adds a t-test to the list of analyses to run
1467                 newTest = genericStatTest.createStatTest('ttest','sosObj',obj,varargin{:});
1468                 obj.sosstattests = [obj.sosstattests {newTest}];
1469
1470                 % if there is a history object at work, let it know that a
1471                 % new stat test has been added.
1472                 if isempty(obj.histObj) == 0
1473                     obj.histObj.addStatTestName(newTest.name);
1474                 end
1475
1476              verbosePrint('t-test added...',  ...
1477                     'sos_addttest_end');
1478         end
1479
1480         %% addtzest(sample1, sample2, s1ColName, s2ColName, type, ...) METHOD
1481         function addztest(obj, varargin)
1482                 %adds a z-test to the list of analyses to run
1483
1484                 % NOTE: If additional, more general types of z-tests are
1485                 % added, this will need to be conditionalized so that
1486                 % sosCorrelTest is not chosen by default...
1487                 newTest = genericStatTest.createStatTest('matchCorrel','sosObj',obj,varargin{:});
1488                 obj.sosstattests = [obj.sosstattests {newTest}];
1489
1490                 % if there is a history object at work, let it know that a
1491                 % new stat test has been added.
1492                 if isempty(obj.histObj) == 0
1493                     obj.histObj.addStatTestName(newTest.name);
1494                 end
1495
1496              verbosePrint('z-test added...',  ...
1497                     'sos_addztest_end');
1498         end
1499
1500
1501         %% addtzest(sample1, sample2, s1ColName, s2ColName, type, ...) METHOD
1502         function addkstest(obj, varargin)
1503                 %adds a kstest to the list of analyses to run
1504
1505                 % NOTE: If additional, more general types of kstests are
1506                 % added, this will need to be conditionalized so that
1507                 % sosCorrelTest is not chosen by default...
1508                 newTest = genericStatTest.createStatTest('matchUniform','sosObj',obj,varargin{:});
1509                 obj.sosstattests = [obj.sosstattests {newTest}];
1510
1511                 % if there is a history object at work, let it know that a
1512                 % new stat test has been added.
1513                 if isempty(obj.histObj) == 0
1514                     obj.histObj.addStatTestName(newTest.name);
1515                 end
1516
1517              verbosePrint('ks-test added...',  ...
1518                     'sos_addkstest_end');
1519         end
1520
1521
1522
1523         function pass = doStatTests(obj,varargin)
1524             % runs the stat tests and indicates if all passed the user
1525             % hypotheses.
1526             %
1527             %PARAMETERS:
1528             %   'reportStyle'/'short'|'full' - style of report to be printed.
1529             %                               Either short or long
1530             %
1531             % RETURNS:
1532             %   NaN if user had no hypotheses about any of the tests that
1533             %   were run.  1 if there were hypotheses and all hypotheses
1534             %   passed their tests.  0  otherwise.
1535
1536            p = inputParser;
1537            p.addParamValue('reportStyle','short', ...
1538                     @(reportStyle)any([strcmp(reportStyle,'short') ...
1539                                     strcmp(reportStyle,'full') ...
1540                                     strcmp(reportStyle,'none')]));
1541            p.parse(varargin{:});
1542
1543            if strcmp(p.Results.reportStyle,'none') == 0
1544                 verbosePrint([char(10),'Running all stat tests:'],...
1545                             'sos_doStatTests_begin');
1546            end
1547             pass = NaN;
1548
1549             %
1550
1551
1552             for i=1:length(obj.sosstattests)
1553                 userHypothesis = obj.sosstattests{i}.runTest(varargin{:});
1554
1555                 if userHypothesis == 0
1556                     pass = 0;
1557                 % if a hypothesis passes (as opposed to being NaN), set the
1558                 % condition to pass;  If a hypothesis has already failed,
1559                 % it cannot pass
1560                 elseif userHypothesis == 1 && isnan(pass)
1561                     pass = 1;
1562                 end
1563             end
1564         end % doStatTests
1565
1566         %% function deltaCostPercentiles() METHOD
1567         function deltaCostPercentiles(obj)
1568             % displays the breakdown of deltaCost values per decile and
1569             % other important percentiles
1570
1571             %one over 100 so that we get the 100th decile
1572             deciles = 0:10:101;
1573             scores = prctile(obj.deltaCostLog, deciles);
1574
1575             %let the user know how many observations entered into the delta
1576             %cost report
1577             verbosePrint(['Deciles for deltaCost in last block:',char(10), ...
1578                 '(',num2str(min(length(obj.deltaCostLog),obj.curIt)),...
1579                 ' iterations total; numIt < blockSize in first block)',char(10)], ...
1580                         'sos_deltaCostPercentiles_Header');
1581
1582
1583            values = '';
1584            for i=1:length(deciles)
1585                line=sprintf('\t%1.0f:  \t %+10.8f \n',deciles(i),scores(i));
1586                values = [values line]; %#ok<AGROW>
1587            end
1588
1589            verbosePrint(values, 'sos_deltaCostPercentiles_Scores');
1590
1591
1592            %print out information that could be helpful for configuring the
1593            %expAnneal function
1594
1595            percentiles = [2.5 97.5];
1596            scores = prctile(obj.deltaCostLog, percentiles);
1597
1598            deltaCost95 = scores(2) - scores(1);
1599
1600            msg = sprintf('\n\n 97.5th - 2.5th percentile deltaCost: %10.8f\n\n', ...
1601                         deltaCost95);
1602
1603            verbosePrint(msg, 'sos_deltaCostPercentiles_deltaCost95');
1604
1605
1606         end
1607
1608     end %end methods
1609
1610     methods (Static)
1611
1612         %% p = sosInputParser() STATIC METHOD
1613         function p = sosInputParser()
1614             % returns an input parser for the sos constructor args
1615             %
1616             %CALL:
1617             % p = sos.sosInputParser()
1618             %
1619             %SYNOPSIS:
1620             % returns an input parser for the sos constructor args
1621             %
1622             %PARAMETERS:
1623             %   Same as object constructor
1624             %
1625             %EXAMPLE:
1626             % p = sos.sosInputParser()
1627             %
1628
1629              p = inputParser;
1630
1631              %use NaN as null, since matlab doesn't support standard
1632              %NULL
1633
1634              p.addParamValue('maxIt',  sos.maxIt_def, ...
1635                 @(maxIt)validateattributes(maxIt, {'numeric'}, ...
1636                 {'scalar', 'integer', 'positive', '>', 0}));
1637             p.addParamValue('pSwapFunction',sos.pSwapFunction_def, ...
1638                 @(pSwapFunction)ischar(pSwapFunction));
1639             p.addParamValue('targSampleCandSelectMethod',sos.targSampleCandSelectMethod_def, ...
1640                 @(targSampleCandSelectMethod)ischar(targSampleCandSelectMethod));
1641             p.addParamValue('feederdfCandSelectMethod',sos.feederdfCandSelectMethod_def, ...
1642                 @(feederdfCandSelectMethod)ischar(feederdfCandSelectMethod));
1643             p.addParamValue('reportInterval',sos.reportInterval_def, ...
1644                 @(reportInterval)validateattributes(reportInterval, {'numeric'}, ...
1645                 {'scalar', 'integer', 'positive', '>', 0}));
1646             p.addParamValue('stopFreezeIt',sos.stopFreezeIt_def, ...
1647                 @(stopFreezeIt)validateattributes(stopFreezeIt, {'numeric'}, ...
1648                 {'scalar', 'integer', 'positive', '>', 0}));
1649             p.addParamValue('statInterval',sos.statInterval_def, ...
1650                 @(statInterval)validateattributes(statInterval, {'numeric'}, ...
1651                 {'scalar', 'integer', 'positive', '>', 0}));
1652             p.addParamValue('statTestReportStyle',sos.statTestReportStyle_def, ...
1653                 @(statTestReportStyle)any(...
1654                     [strcmp(statTestReportStyle,'short'), ...
1655                      strcmp(statTestReportStyle,'full')]));
1656             p.addParamValue('blockSize',sos.blockSize_def, ...
1657                 @(statInterval)validateattributes(statInterval, {'numeric'}, ...
1658                 {'scalar', 'integer', 'positive', '>', 0}));
1659
1660
1661         end
1662     end
1663
1664     methods (Static, Access = private)
1665         %% parseConstructorArgs PRIVATE STATIC METHOD
1666         function p = parseConstructorArgs(varargin)
1667             %parses the constructor arguments
1668             %
1669             % CALL:
1670             % p = sos.parseConstructorArgs(varargin);
1671             %
1672             %parses the arguments from the  constructor.  Default
1673             %values are substituted where appropriate.  Returns a struct
1674             %with the parsed args
1675             %
1676             %PARAMETERS:
1677             % SAME as sos CONSTRUCTOR
1678             %
1679             %RETURNS:
1680             %    p - parsed constructor input
1681
1682              varargin = varargin{1};
1683
1684              p = sos.sosInputParser();
1685              p.parse(varargin{:});
1686
1687              if any(strcmp(p.UsingDefaults,'maxIt'))
1688                  verbosePrint(['    Defaulting to ',  ...
1689                      num2str(p.Results.maxIt), ' maximum iterations'], ...
1690                     'sos_parseConstructor_defaultMaxIt');
1691              end
1692
1693              if any(strcmp(p.UsingDefaults,'pSwapFunction'))
1694                  verbosePrint(['    Defaulting to ', ...
1695                      (p.Results.pSwapFunction), ' pSwapFunction'], ...
1696                     'sos_parseConstructor_pSwapFunction');
1697              end
1698
1699              if any(strcmp(p.UsingDefaults,'targSampleCandSelectMethod'))
1700                  verbosePrint(['    Defaulting to ', ...
1701                      (p.Results.targSampleCandSelectMethod), ...
1702                      ' targSample Candidate Selection Method'], ...
1703                     'sos_parseConstructor_targSampleCandSelectMethod');
1704              end
1705
1706              if any(strcmp(p.UsingDefaults,'feederdfCandSelectMethod'))
1707                  verbosePrint(['    Defaulting to ', ...
1708                      (p.Results.feederdfCandSelectMethod), ...
1709                      ' feederdf Candidate Selection Method'], ...
1710                     'sos_parseConstructor_feederdfCandSelectMethod');
1711              end
1712
1713              if any(strcmp(p.UsingDefaults,'reportInterval'))
1714                  verbosePrint(['    Defaulting to ', ...
1715                      num2str(p.Results.reportInterval), ...
1716                      ' iterations between reports'], ...
1717                     'sos_parseConstructor_reportInterval');
1718              end
1719
1720              if any(strcmp(p.UsingDefaults,'stopFreezeIt'))
1721                  verbosePrint(['    Defaulting to ', ...
1722                      num2str(p.Results.stopFreezeIt), ...
1723                      ' of same frozen cost before stopping'], ...
1724                     'sos_parseConstructor_stopFreezeIt');
1725              end
1726
1727
1728              if any(strcmp(p.UsingDefaults,'statInterval'))
1729                  verbosePrint(['    Defaulting to ', ...
1730                      num2str(p.Results.statInterval), ...
1731                      ' intervals between stat reports'], ...
1732                     'sos_parseConstructor_statReports');
1733              end
1734
1735              if any(strcmp(p.UsingDefaults,'statTestReportStyle'))
1736                  verbosePrint(['    Defaulting to ', ...
1737                      p.Results.statTestReportStyle, ...
1738                      ' style stat reports'], ...
1739                     'sos_parseConstructor_statReports');
1740              end
1741
1742         end % parseConstructorArgs
1743     end
1744
1745 end