Description of validateRealNumber
Home > src > validateRealNumber.m
validateRealNumber
PURPOSE
- helper function to validate that a string represents a real number
SYNOPSIS
function flag = validateRealNumber(strNum,errmsg,errtitle)
DESCRIPTION
 - helper function to validate that a string represents a real number
 copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
    This file is part of SOS
    SOS is free software: you can redistribute it and/or modify
    it for academic and non-commercial purposes
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.  For commercial or for-profit
    uses, please contact the authors (sos@cnbc.cmu.edu).
    SOS is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
createHardBoundConstraint_Dialog - create hard bound constraint dialog
createMatchUniformkstest_Dialog - create uniformity ks-test dialog
createSingleSampleSoftDistanceConstraint_Dialog - create single sample soft distance constraint dialog
createSoftEntropyConstraint_Dialog - create soft entropy constraint dialog
createSoftMatchCorrelDistanceConstraint_Dialog - create soft match correlation constraint dialog
createSoftMetaConstraint_Dialog - create soft meta-constraint dialog
createTwoSampleSoftDistanceConstraint_Dialog - create two sample soft distance constraint dialog
createsinglesamplettest_Dialog - create single sample t-test dialog
expAnneal_Dialog - create expAnneal dialog
maxpDecrease_Dialog dialog used for calculating the largest p-decrease value
numSteps_Dialog dialog used to calculate the nubmer of temperature-lowering steps
SOURCE CODE
% - helper function to validate that a string represents a real number
%
% copyright 2009-2012 Blair Armstrong, Christine Watson, David Plaut
%
%    This file is part of SOS
%
%    SOS is free software: you can redistribute it and/or modify
%    it for academic and non-commercial purposes
%    under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.  For commercial or for-profit
%    uses, please contact the authors (sos@cnbc.cmu.edu).
%
%    SOS is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%    You should have received a copy of the GNU General Public License
%    along with SOS (see COPYING.txt).
%    If not, see <http://www.gnu.org/licenses/>.
function flag = validateRealNumber(strNum,errmsg,errtitle)
    % validates that the string represents a real number
    valid = str2double(strNum);
    if isnan(valid)
        % name is not currently valid, tell the user.
        msgbox(errmsg,...
                errtitle);
       flag = false;
    else
        flag = true;
    end
end